var sv=sv||{};
(function(){var a=window.sv,c,b=["debug","info","warn","error"],e={debug:!1,info:!0,warn:!0,error:!0};(function(){var a=0,d=b.length,h;for(c="undefined"===typeof window.console?{log:function(){},debug:function(){},info:function(){},warn:function(){},error:function(){}}:window.console;a<d;a++)h=b[a],"undefined"===typeof c[h]&&(c[h]=c.log)})();var f=function(b,a,h){try{if("string"!==typeof a||h||(h=a),e[b])if(a&&a.hasOwnProperty("toString"))c[b](a.toString()+" : "+h);else c[b](h)}catch(f){}};a.Log=
{debug:function(a,d){f(b[0],a,d)},info:function(a,d){f(b[1],a,d)},warn:function(a,d){f(b[2],a,d)},error:function(a,d){f(b[3],a,d)},setTraceLevel:function(a){var d;a:if(b.indexOf)d=b.indexOf(a);else{for(d=b.length-1;0<=d;d--)if(b[d]===a)break a;d=-1}for(var h=0,c=b.length;h<c;h++)a=b[h],e[a]=h>=d},getTraceLevels:function(){return e}}})();
(function(a,c){a.TemplateUtil=function(){var a={},e;e=function(c,g){var d=/\W/.test(c)?new Function("obj","var p=[],print=function(){p.push.apply(p, arguments);};with(obj){p.push('"+c.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');"):a[c]=a[c]||e(document.getElementById(c).innerHTML);return g?d(g):d};return{template:e,htmlEncode:function(a){return c("<div/>").text(a).html()}}}()})(window.sv,
window.$svjq);
(function(){var a,c=window.sv,b=window.$svjq,e=c.Log;(function(){var c=b("html").attr("lang");a=-1!==c.indexOf("-")?c.toLowerCase().substring(0,c.indexOf("-")):c.toLowerCase();e.info(this,"Using system language: "+a)})();var f=function(a,b){a=a.split(".");for(var c=0;c<a.length;c++)b=b[a[c]];return b};c.i18n={getText:function(g,d,h){try{var k=f(g,c.i18n),l=k[a][d];return l?h?(b.isArray(h)||(h=[h]),l.replace(/\{(\d+)\}/g,function(a,b){return h[b]})):l:(e.warn(this,"Unable to find property: "+g+"."+
a+"."+d+", trying default language: en"),k.en[d]||d)}catch(m){try{return k.en[d]||d}catch(n){return e.error(this,"Unable to find property: "+g+"."+a+"."+d),d}}},getLanguage:function(){return a}}})();(function(){var a={BACKSPACE:8,TAB:9,RETURN:13,SHIFT:16,CTRL:17,ALT:18,BREAK:19,CAPS_LOCK:20,ESC:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT:37,UP:38,RIGHT:39,DOWN:40,INSERT:45,DEL:46,COMMA:188};window.sv.KeyUtil={KEY:a,getKeyCodeFromEvent:function(a){return a.keyCode?a.keyCode:a.which},isNonTextModifiableKeyCode:function(c){switch(c){case a.TAB:case a.RETURN:case a.SHIFT:case a.CTRL:case a.ALT:case a.BREAK:case a.CAPS_LOCK:case a.ESC:case a.PAGE_UP:case a.PAGE_DOWN:case a.END:case a.HOME:case a.LEFT:case a.UP:case a.RIGHT:case a.DOWN:case a.INSERT:return!0}return!1}}})();
(function(){var a=window.sv,c=window.$svjq,b=window.navigator.platform,e=-1!==b.toLowerCase().indexOf("mac"),f=-1!==b.toLowerCase().indexOf("win"),b=-1!==b.toLowerCase().indexOf("linux"),g=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?!0:!1,d=!g,h=function(){var a=window.navigator.userAgent;return/iPhone/i.test(a)||/iPod/i.test(a)||/iPad/i.test(a)||/mobile/i.test(a)}(),k="placeholder"in document.createElement("input"),l=document.documentElement,m=" -webkit- -moz- -o- -ms- ".split(" "),n=function(a,
b,d,c){var e,h,g=document.createElement("div"),m=document.body,f=m||document.createElement("body");if(parseInt(d,10))for(;d--;)e=document.createElement("div"),e.id=c?c[d]:"sitevision"+(d+1),g.appendChild(e);d=['&#173;<style id="ssitevision">',a,"</style>"].join("");g.id="sitevision";(m?g:f).innerHTML+=d;f.appendChild(g);m||(f.style.background="",f.style.overflow="hidden",h=l.style.overflow,l.style.overflow="hidden",l.appendChild(f));a=b(g,a);m?g.parentNode.removeChild(g):(f.parentNode.removeChild(f),
l.style.overflow=h);return!!a},s=function(){var a=function(){var a;"ontouchstart"in window||window.DocumentTouch&&document instanceof window.DocumentTouch?a=!0:n(["@media (",m.join("touch-enabled),("),"sitevision){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop});return a}();c("html").addClass(a?"sv-touch":"sv-no-touch");return a}();a.ClientUtil={isMac:e,isWindows:f,isLinux:b,isMobileDevice:h,supportsPlaceholder:k,isTouchDevice:s,isIOSDevice:g,isJavaInstalled:d}})();
(function(){var a=window.$svjq,c=window.sv,b={},e=function(a,d,c){var e="sv-event-"+a,f=a&&0===a.indexOf("server-");c=c||window;b[e]||(b[e]=[]);b[e].push({handler:d,scope:c});f&&g(a)},f=function(c,e){var g="sv-event-"+c,f=c&&0===c.indexOf("server-"),n=b[g];n&&(f&&d(c),n=e?a.grep(n,function(a){return"undefined"===typeof a.handler.guid?a.handler!==e:a.handler.guid!==e.guid}):[],b[g]=n)},g=function(b){var d=a.Deferred(),g=b.substring(7);if("undefined"!==g)return c._serverEventChannels=c._serverEventChannels||
[],c._serverEventChannels.push({subscribe:g}),e("_server-event-connected-"+g,function(){d.resolve();f("_server-event-connected-"+g);f("_server-event-failed-"+g)}),e("_server-event-failed-"+g,function(){d.reject();f("_server-event-connected-"+g);f("_server-event-failed-"+g)}),d.promise()},d=function(a){a=a.substring(7);c._serverEventChannels.push({unsubscribe:a})};c.Events={on:e,off:f,onServerEvent:function(a,d,c){var e="sv-event-"+a;c=c||window;b[e]||(b[e]=[]);b[e].push({handler:d,scope:c});return g(a)},
trigger:function(c){var d=b["sv-event-"+c],e;d&&(e=[],a.each(arguments,function(a,b){0<a&&e.push(b)}),a.each(d,function(a,b){b.handler.apply(b.scope,e)}))},types:{notifyUser:"notify-user",updateRelativeDates:"update-relative-dates",updateOembedLinks:"update-oembed-links",updateVideoLinks:"update-video-links",updateLikables:"update-likables",fileAdded:"file-added",activityUpdated:"activity-updated",activityCreated:"activity-created",activityDeleted:"activity-deleted",groupPageViewed:"group-page-viewed",
popoverCreated:"popover-created",showMessages:"show-messages"},handleServerSideEvent:function(d,c){a.each(b["sv-event-server-"+d],function(a,b){b.handler.call(window,c)})}}})();
(function(){var a=window.sv,c=window.$svjq,b=a.Events,e=a.i18n,f=function(a,b){return e.getText("util.errorutil",a,b)},g=function(a,d){b.trigger(b.types.notifyUser,{type:"error",heading:a,message:d})},d=function(a){if(0===a.readyState)g(f("connectionErrorMessageTitle"),f("connectionErrorMessage"));else{if(void 0!==a.responseText){var b;b="object"===typeof a.responseText?a.responseText:c.parseJSON(a.responseText);if(void 0!==b.title&&void 0!==b.message){g(b.title,b.message);return}}g(f("errorMessageTitle"),
f("errorMessage",a.status))}};a.ErrorUtil={handleBackboneError:function(a,b,c){d(b)},handleAjaxFailure:d}})();
(function(){var a=window.$svjq,c=window.sv.Events,b=a("<div/>",{"class":"bootstrap sv-notifier"});b.appendTo("body");var e=function(b){b.fadeOut("slow",function(){a(this).remove()})},f=function(b,d,c){var e=a("<div></div>",{"class":"alert",css:{lineHeight:"20px",fontSize:"14px"}}).append('<button type="button" class="close" data-dismiss="alert">\u00d7</button>');e.addClass("alert-block alert-"+b);if(d){b=a("<p />");var f=a("<strong />");f.text(d);b.append(f);e.append(b)}c&&(d=a("<p />"),d.text(c),
e.append(d));return e};c.on(c.types.notifyUser,function(a){var c=f(a.type,a.heading,a.message);e(b.find(".sv-fn-transient-message"));if(a.onClick)c.on("click",":not(.close)",a.onClick);a["transient"]&&c.addClass("sv-fn-transient-message");a.timer&&setTimeout(function(){e(c)},1E3*a.timer);0===b.parent().length&&b.appendTo("body");c.prependTo(b)})})();
(function(a,c,b,e,f){c.DialogUtil=function(){function c(b){var d;d=a.extend({title:"",modalBody:"",footerButtons:"",titleHelp:"",errorContent:""},b);if("string"===typeof d.modalBody)return a(e(l,d));d.modalBody="";d=a(e(l,d));d.find(".modal-body").append(b.modalBody);return d}function d(){var a,c;c=e(k,{classNames:"btn-primary",attributes:'data-dismiss="modal" data-ok="true"',text:b.getText("util.dialogutil","ok",void 0)});a=e(k,{classNames:"",attributes:'data-dismiss="modal" data-ok="false"',text:b.getText("util.dialogutil",
"cancel",void 0)});return c+a}function h(b,c){b.on("shown",function(){var c=b.find("[data-fn-request-focus]");c.length?c.first().focus():b.find("input").first().focus();a(document.body).addClass("modal-open")});b.on("hidden",function(){!1!==c&&b.remove();a(document.body).removeClass("modal-open")})}var k,l;k='<button <%= attributes %> class="btn <%= classNames %> "><%= text %></button>';l='<div class="modal hide fade bootstrap"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button class="close" type="button" data-dismiss="modal">&times;</button><h3><%= title %></h3></div><div class="modal-body"><%= titleHelp %><%= errorContent %><%= modalBody %></div><div class="modal-footer"><%= footerButtons %></div></div></div></div>';
return{showInputDialog:function(b,n,k,l,q){var p;k=e(k?'<textarea class="ui-widget-content ui-corner-all sv-eventfeed-input sv-eventfeed-message-input"><%= value %></textarea>':'<input type="text" value="<%= value %>" class="ui-widget-content ui-corner-all sv-eventfeed-input">',{value:l||""});n=e('<form class="form-horizontal"><div class="control-group"><label class="control-label"><%= label %></label><div class="controls"><%= input %></div></div></form>',{input:k,label:n||""});p=c({title:f(b),modalBody:n,
footerButtons:d()});p.on("click",".modal-footer .btn",function(){a(this).data("ok")?q({result:!0,text:p.find(".sv-eventfeed-input").val()}):q({result:!1})});p.on("submit","form",function(a){a.preventDefault();p.modal("hide");q({result:!0,text:p.find(".sv-eventfeed-input").val()})});h(p);p.modal();return p},showConfirmDialog:function(b,e,k){b=c({title:f(b),modalBody:e,footerButtons:d()});b.on("click",".modal-footer .btn",function(){k(!!a(this).data("ok"))});h(b);b.modal();return b},showMessageDialog:function(a,
b,d){d=e(k,{classNames:"btn-primary",attributes:'data-dismiss="modal"',text:d||"Close"});a=c({title:f(a),modalBody:b,footerButtons:d});h(a);a.modal();return a},showDialog:function(b){var d,l,r;d=b.titleHelp?e("<p><%= text %></p>",{text:b.titleHelp}):"";r=b.errorTitle&&b.errorMsg?e('<div class="alert alert-error" style="display: none"><h4 class="alert-title"><%= errorTitle %><h4><p class="alert-message"><%= errorMsg %></p></div>',{errorTitle:b.errorTitle,errorMsg:b.errorMsg}):"";d=c({title:f(b.title),
modalBody:b.body,titleHelp:d,errorContent:r});l=d.find(".modal-footer");a.each(b.buttons,function(b,c){var d,f;f=c.skipDismiss?"":' data-dismiss="modal" ';d=c.primary?" btn-primary ":"";d+=c.danger?" btn-danger ":"";d=a(e(k,{classNames:d,text:c.text,attributes:f}));if(c.callback)d.on("click",c.callback);l.append(d)});if(b.shownCallback&&"function"===typeof b.shownCallback)d.on("shown",function(a){b.shownCallback.call(this,a)});if(!1!==b.removeOnHide&&b.hiddenCallback&&"function"===typeof b.hiddenCallback)d.on("hidden",
function(a){b.hiddenCallback.call(this,a)});h(d,b.removeOnHide);d.modal();return d}}}()})(window.$svjq,window.sv,window.sv.i18n,window.sv.TemplateUtil.template,window.sv.TemplateUtil.htmlEncode);(function(){var a=window.sv,c=a.Log;a.ObjectUtil={getObjectId:function(a){if(!a)return null;try{return a.substring(4).replace("_",".")}catch(e){c.error(this,"Message: "+e)}},getHtmlId:function(a){if(!a)return null;try{return"svid"+a.replace(".","_")}catch(e){c.error(this,"Message: "+e)}}}})();
(function(a){a.fn.sortableViewLayout=function(){return this.each(function(){var c=a(this),b=c.attr("id"),e=c.hasClass("sv-horizontal");c.hasClass("ui-sortable")&&c.sortable("destroy");var f=c.data("connect-with");c.sortable({containment:f?!1:"#"+b,connectWith:f?".sv-sortable-view-container":!1,placeholder:"sv-view-selection-placeholder",forcePlaceholderSize:!0,distance:10,items:".sv-view-mouseover",opacity:.6,stop:function(a,b){b.item.hide();b.item.show("blind",200)},update:function(b,d){var f=a(this);
0<f.find(d.item).length&&(e?d.item.addClass("sv-horizontal-column"):d.item.removeClass("sv-horizontal-column"));for(var k=[],f=f.sortable("toArray"),l=0;l<f.length;l++){var m=c.find("#"+f[l]);m.closest(".sv-sortable-view-container").attr("id")===c.attr("id")&&k.push(m.attr("id"))}k=k.join(",");k=k.replace(/svid|,,/g,"");k=k.replace(/_/g,".");a.post(c.data("view-container-url")+"&return=none&updateViews=true&viewId="+k);c.find(".sv-sortable-view-container").push(c)}})})};a(function(){function c(a,
b,c){b=b.attr("id").replace("svid","").replace("_",".");a=a.attr("href");return"/"+a.substring(a.indexOf("page=")+5,a.length)+"/"+b+".xml?sv.state="+c+"&sv.url="+b}var b=a("body");b.on("click",".sv-view-selector",function(){var b=a(this),c=b.attr("href"),g=b.attr("id").substr(15),d=a("#sv-view-selector-dialog-"+g);0<d.length?d.svDialog("open"):(d=a("<div/>",{id:"sv-view-selector-dialog-"+g}),d.on("open:dialog.sv-dialog",function(){var b=a(this);b.find(".sv-custom-views-list").sortable({containment:b.closest(".sv-dialog"),
axis:"y"})}),d.svDialog({title:sv.i18n.getText("util.viewutil","selectView"),open:!0,url:c,modal:!0,buttons:[{text:sv.i18n.getText("common","save"),type:"primary",callback:function(){var b=d.find("form");a.post(c,b.serialize(),function(){a.get(sv[g].layoutURL,function(b){a("#"+g).html(b);a(".sv-sortable-view-container").sortableViewLayout();d.svDialog("close")})})}},{text:sv.i18n.getText("common","cancel"),type:"link",callback:function(){d.svDialog("close")}}]}));return!1});b.on("click",".sv-layout-minimize",
function(){var b=a(this),f=b.closest("[id^=svid10_]"),g=c(b,f,"minimized");a.get(g,function(a){b.closest(".sv-toolbar").siblings().hide();f.html(a)});return!1});b.on("click",".sv-layout-restore",function(){var b=a(this),f=b.closest("[id^=svid10_]"),b=c(b,f,"normal");a.get(b,function(a){f.html(a).show()});return!1});b.on("click",".sv-portlet-restore",function(){var b=a(this),c=b.closest(".pagecontent"),g=c.attr("id").replace("svid","").replace("_","."),d=b.attr("href"),b=d.substring(d.indexOf("page=")+
5,d.length),d=d.substring(d.indexOf("?"),d.length);a.get("/"+b+"/"+g+".xml"+d,function(a){c.html(a).show()});return!1});a(".sv-sortable-view-container").sortableViewLayout()})})($svjq);
(function(){var a=window.sv,c=window.$svjq;a.ImageUtil={getImageDimension:function(a){var c=a.maxWidth,f=a.minWidth,g=a.maxHeight,d=a.minHeight,h=0;a={width:a.width,height:a.height};a.width>c?(h=c/a.width,a.width=c,a.height*=h):a.width<f&&(h=f/a.width,a.width=f,a.height*=h);a.height>g?(h=g/a.height,a.height=g,a.width*=h):a.height<d&&(h=d/a.height,a.height=d,a.width*=h);return a},changeImageSrcAndSize:function(b,e,f,g){a.PageContext.inEditMode||c(b).attr("src",e).load(function(){c(this).css({"max-width":f,
"max-height":g})})}}})();
(function(){var a=window.$svjq,c=window.sv;a(function(){a(".sv-portlet, .sv-text-portlet, .sv-custom-module").dblclick(function(b){if(b.shiftKey&&!top.SiteVisionEditor){var e;e=(e=/[\?&]instantEdit=([^&#]*)/.exec(window.location.href))?e[1]||null:null;if("true"!==e)if(a(b.currentTarget).hasClass("sv-text-portlet"))top.location.href="/edit/"+c.PageContext.pageId;else{e=top.location;var f="/edit/"+c.PageContext.pageId+"/";b=(b=a(b.currentTarget).attr("id"))?b.substring(4).replace("_","."):null;e.href=
f+b+"/settings"}}})})})();
(function(){window.sv.DateUtil={fromISO:function(a){var c=new Date("2011-06-02T09:34:29+02:00");if(c&&1307000069E3===+c)return new Date(a);var b,c=/^(\d{4}\-\d\d\-\d\d([tT ][\d:\.]*)?)([zZ]|([+\-])(\d\d):(\d\d))?$/.exec(a)||[];if(c[1]){a=c[1].split(/\D/);b=0;for(var e=a.length;b<e;b++)a[b]=parseInt(a[b],10)||0;--a[1];a=new Date(Date.UTC.apply(Date,a));if(!a.getDate())return NaN;c[5]&&(b=60*parseInt(c[5],10),c[6]&&(b+=parseInt(c[6],10)),"+"===c[4]&&(b*=-1),b&&a.setUTCMinutes(a.getUTCMinutes()+b));
return a}return NaN},moment2PhpFormat:function(a){return a.replace("HH","0").replace("H","1").replace("hh","2").replace("h","3").replace("mm","4").replace("m","4").replace("ss","5").replace("s","5").replace("0","H").replace("1","G").replace("2","h").replace("3","g").replace("4","i").replace("5","s")}}})();
(function(){window.sv.CollectionUtil={getKeys:function(a){if(Object.keys)return Object.keys(a);var c=[],b;for(b in a)a.hasOwnProperty(b)&&c.push(b);return c},removeAll:function(a,c){for(var b=[],e=0;e<a.length;e++){for(var f=!1,g=0;g<c;g++)if(a[e]===c[e]){f=!0;break}f||b.push(a[e])}return b},contains:function(a,c){if(void 0!==a){if(Array.prototype.indexOf)return-1<c.indexOf(a);for(var b in c)if(b===a)return!0}return!1}}})();
(function(a){a.fn.bsPopoverAriaButton||(a.fn.bsPopoverAriaButton=function(){var a=this;a.on("hide.bs.modal",function(){a.attr("aria-pressed",!1)}).on("show.bs.modal",function(){a.attr("aria-pressed",!0)}).on("keydown",function(a){32===a.keyCode&&a.preventDefault()}).on("keyup",function(a){32===a.keyCode&&this.click()}).attr({role:"button"});return this})})(window.$svjq);
(function(){function a(a){!/get/i.test(a.type)&&a.data&&b.isPlainObject(a.data)&&(a.processData=!1,a.data=JSON.stringify(a.data));return b.ajax(a)}var c=window.sv,b=window.$svjq,e={type:"get",dataType:"json",headers:{"Accept-Language":window.sv.i18n.getLanguage()}},f=b.extend({},{contentType:"application/json; charset=utf-8"},e),g={get:b.extend({},e),put:b.extend({},f,{type:"put"}),post:b.extend({},f,{type:"post"}),"delete":b.extend({},f,{type:"delete"})};c.Ajax={doGet:function(c){return a(b.extend({},
g.get,c))},doPut:function(c){return a(b.extend({},g.put,c))},doPost:function(c){return a(b.extend({},g.post,c))},doDelete:function(c){return a(b.extend({},g["delete"],c))}}})();sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.util=sv.i18n.portlet.util||{};sv.i18n.portlet.util.addgrouputil=sv.i18n.portlet.util.addgrouputil||{};sv.i18n.portlet.util.addgrouputil.de={};
sv.i18n.portlet.util.addgrouputil.en={object_already_exists:"A group with the same name already exists!",name:"Name",typeHelp:"Open - anyone can join<br/>Moderated - open but only administrator can add members<br/>Closed - only members can see the group",invalid_object_name:"Invalid group name",nameHelp:"Group name",descriptionHelp:"Group description",templateHelp:"Select group type",createGroupError:"Error",createGroupLabel:"Create new group",open:"Open",closed:"Closed",groupAlreadyExists:"A group with the same name already exists!",
type:"Status",createGroup:"Create group",description:"Description",template:"Group type",member_moderated:"Moderated"};
sv.i18n.portlet.util.addgrouputil.fi={object_already_exists:"Samanniminen ryhm\u00e4 on jo olemassa!",name:"Nimi",typeHelp:"Avoin - kaikki voivat p\u00e4\u00e4st\u00e4 j\u00e4seneksi<br/>Moderoitu - vain moderaattori voi hyv\u00e4ksy\u00e4 j\u00e4seneksi<br/>Suljettu - vain j\u00e4senet n\u00e4kev\u00e4t ryhm\u00e4n",invalid_object_name:"Virheellinen ryhm\u00e4n nimi",nameHelp:"Ryhm\u00e4n nimi",descriptionHelp:"Ryhm\u00e4n kuvaus",templateHelp:"Valitse ryhm\u00e4n tyyppi",createGroupError:"Virhe",
createGroupLabel:"Luo uusi ryhm\u00e4",open:"Avoin",closed:"Suljettu",groupAlreadyExists:"Samanniminen ryhm\u00e4 on jo olemassa!",type:"Status",createGroup:"Luo ryhm\u00e4",description:"Kuvaus",template:"Tyyppi",member_moderated:"Moderoitu"};
sv.i18n.portlet.util.addgrouputil.no={object_already_exists:"En gruppe med samme navn finnes allerede!",name:"Navn",typeHelp:"\u00c5pen \u2013 alle kan bli medlem<br/>Moderert \u2013 bare administratorer kan legge til medlemmer<br/>Lukket \u2013 bare medlemmer kan se gruppen",invalid_object_name:"Feil gruppenavn",nameHelp:"Gruppens navn",descriptionHelp:"Gruppens beskrivelse",templateHelp:"Velg gruppetype",createGroupError:"Feil",createGroupLabel:"Opprett ny gruppe",open:"\u00c5pen",closed:"Lukket",
groupAlreadyExists:"En gruppe med samme navn finnes allerede!",type:"Status",createGroup:"Opprett gruppe",description:"Beskrivelse",template:"Type",member_moderated:"Moderert"};
sv.i18n.portlet.util.addgrouputil.sv={object_already_exists:"En grupp med samma namn finns redan!",name:"Namn",typeHelp:"\u00d6ppen - alla kan bli medlemmar<br/>Modererad - endast administrat\u00f6rer kan l\u00e4gga till medlemmar<br/>Sluten - endast medlemmar kan se gruppen",invalid_object_name:"Felaktigt gruppnamn",nameHelp:"Gruppens namn",descriptionHelp:"Gruppens beskrivning",templateHelp:"V\u00e4lj grupptyp",createGroupError:"Fel",createGroupLabel:"Skapa ny grupp",open:"\u00d6ppen",closed:"Sluten",
groupAlreadyExists:"En grupp med samma namn finns redan!",type:"Status",createGroup:"Skapa grupp",description:"Beskrivning",template:"Typ",member_moderated:"Modererad"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.archive=sv.i18n.portlet.archive||{};sv.i18n.portlet.archive.archive=sv.i18n.portlet.archive.archive||{};sv.i18n.portlet.archive.archive.de={};sv.i18n.portlet.archive.archive.en={creatingArticle:"Creating article..."};sv.i18n.portlet.archive.archive.fi={creatingArticle:"Luo artikkelia..."};
sv.i18n.portlet.archive.archive.no={creatingArticle:"Oppretter artikkel ..."};sv.i18n.portlet.archive.archive.sv={creatingArticle:"Skapar artikel..."};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.blog=sv.i18n.portlet.blog||{};sv.i18n.portlet.blog.blog=sv.i18n.portlet.blog.blog||{};sv.i18n.portlet.blog.blog.de={};sv.i18n.portlet.blog.blog.en={creatingBlogEntry:"Creating blog entry..."};sv.i18n.portlet.blog.blog.fi={creatingBlogEntry:"Luo blogiyhteytt\u00e4..."};
sv.i18n.portlet.blog.blog.no={creatingBlogEntry:"Oppretter blogginnlegg ..."};sv.i18n.portlet.blog.blog.sv={creatingBlogEntry:"Skapar blogginl\u00e4gg..."};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.bookmarklist=sv.i18n.portlet.social.bookmarklist||{};sv.i18n.portlet.social.bookmarklist.bookmarklist=sv.i18n.portlet.social.bookmarklist.bookmarklist||{};sv.i18n.portlet.social.bookmarklist.bookmarklist.de={};
sv.i18n.portlet.social.bookmarklist.bookmarklist.en={deleteMsg:"Are you sure you want to delete this bookmark?",name:"Name",deleteBookmark:"Delete bookmark?",description:"Description",deleteTitle:"Delete bookmark"};sv.i18n.portlet.social.bookmarklist.bookmarklist.fi={};sv.i18n.portlet.social.bookmarklist.bookmarklist.no={deleteMsg:"Er du sikker p\u00e5 at du vil fjerne aktuelt bokmerke?",name:"Navn",deleteBookmark:"Vil du fjerne bokmerke?",description:"Beskrivelse",deleteTitle:"Fjern"};
sv.i18n.portlet.social.bookmarklist.bookmarklist.sv={deleteMsg:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort aktuellt bokm\u00e4rke?",name:"Namn",deleteBookmark:"Ta bort bookm\u00e4rke?",description:"Beskrivning",deleteTitle:"Ta bort"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.fileview=sv.i18n.portlet.social.fileview||{};sv.i18n.portlet.social.fileview.browse=sv.i18n.portlet.social.fileview.browse||{};
sv.i18n.portlet.social.fileview.browse.de={};
sv.i18n.portlet.social.fileview.browse.en={renameFolderTitle:"Rename folder",renameFolderMessage:"New name",createFolderMessage:"Name",moveNodeSingleMessage:"Are you sure you want to move '{0}' to the current folder?",deleteNodeMultiMessage:"Are you sure you want to delete {0} objects?",moveNodeMultiMessage:"Are you sure you want to move {0} objects to the current folder?",deleteNodeTitle:"Delete",moveNodeTitle:"Move",deleteNodeSingleMessage:"Are you sure you want to delete '{0}'?",createFolderTitle:"Create folder"};
sv.i18n.portlet.social.fileview.browse.fi={renameFolderTitle:"Vaihda kansion nimi",renameFolderMessage:"Uusi nimi",createFolderMessage:"Nimi",moveNodeSingleMessage:"Oletko varma, ett\u00e4 haluat siirt\u00e4\u00e4 '{0}' t\u00e4h\u00e4n kansioon?",deleteNodeMultiMessage:"Oletko varma, ett\u00e4 haluat poistaa {0} kohteen?",moveNodeMultiMessage:"Oletko varma, ett\u00e4 haluat siirt\u00e4\u00e4 {0} kohteen t\u00e4h\u00e4n kansioon?",deleteNodeTitle:"Poista",moveNodeTitle:"Siirt\u00e4\u00e4",deleteNodeSingleMessage:"Oletko varma, ett\u00e4 haluat poistaa '{0}'?",
createFolderTitle:"Luo kansio"};
sv.i18n.portlet.social.fileview.browse.no={renameFolderTitle:"Bytt navn p\u00e5 mappe",renameFolderMessage:"Nytt navn",createFolderMessage:"Navn",moveNodeSingleMessage:'Er du sikker p\u00e5 at du vil flytte "{0}" til denne mappen?',deleteNodeMultiMessage:"Er du sikker p\u00e5 at du vil fjerne {0} objekt?",moveNodeMultiMessage:"Er du sikker p\u00e5 at du vil flytte {0} objekt til denne mappen?",deleteNodeTitle:"Fjern",moveNodeTitle:"Flytt",deleteNodeSingleMessage:'Er du sikker p\u00e5 at du vil fjerne "{0}"?',createFolderTitle:"Opprett mappe"};
sv.i18n.portlet.social.fileview.browse.sv={renameFolderTitle:"Byt namn p\u00e5 mapp",renameFolderMessage:"Nytt namn",createFolderMessage:"Namn",moveNodeSingleMessage:"\u00c4r du s\u00e4ker p\u00e5 du vill flytta '{0}' till denna mapp?",deleteNodeMultiMessage:"\u00c4r du s\u00e4ker p\u00e5 du vill ta bort {0} objekt?",moveNodeMultiMessage:"\u00c4r du s\u00e4ker p\u00e5 du vill flytta {0} objekt denna mapp?",deleteNodeTitle:"Ta bort",moveNodeTitle:"Flytta",deleteNodeSingleMessage:"\u00c4r du s\u00e4ker p\u00e5 du vill ta bort '{0}'?",
createFolderTitle:"Skapa mapp"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.calendar=sv.i18n.portlet.social.calendar||{};sv.i18n.portlet.social.calendar.calendar=sv.i18n.portlet.social.calendar.calendar||{};sv.i18n.portlet.social.calendar.calendar.de={};
sv.i18n.portlet.social.calendar.calendar.en={tuesday:"Tuesday",confirmRemoveMessage:"Are you sure you want to delete the event?",sat:"Sat",description:"Description",buttonTextWeek:"Week",allday:"All day",jun:"Jun",jul:"Jul",apr:"Apr",create:"Add event",may:"May",confirmRemoveTaskRemove:"Yes",titleDay:"dddd d MMM yyyy",mar:"Mar",map:"Map",sunday:"Sunday",columnWeek:"dddd d/MM",confirmRemoveTaskTitle:"Delete",axisFormat:"HH:mm",columnMonth:"ddd",eventState:"Status",february:"February",january:"January",
more:"Read more",wed:"Wed",jan:"Jan",sep:"Sep",event:"Event",aug:"Aug",buttonTextAgendaList:"List",filterMine:"Everybody's",monday:"Monday",filterAll:"Only mine",april:"April",timeFormatAgenda:"HH:mm{ - HH:mm}",noOwner:"Specify an owner",createEvent:"Event",titleWeek:"d [MMM yyyy]{ - d MMM yyyy}",october:"October",timeFormat:"HH:mm",name:"Title",noEnd:"Specify an end date",confirmRemoveTaskSaveInTasks:"No, save in the task list",invalidAllDayTimePeriod:"End date must be the same or after start date",
friday:"Friday",eventDetails:"Details",invalidTimePeriod:"End time must be after start time",wednesday:"Wednesday",november:"November",titleMonth:"MMMM yyyy",june:"June",fri:"Fri",buttonTextDay:"Day",owner:"Owner",task:"Task",confirmRemoveTitle:"Delete",march:"March",saturday:"Saturday",december:"December",august:"August",sun:"Sun",september:"September",oct:"Oct",tue:"Tue",buttonTextToday:"Today",buttonTextMonth:"Month",thursday:"Thursday",thu:"Thu",feb:"Feb",nov:"Nov",july:"July",columnDay:"dddd d/MM",
dec:"Dec",participants:"Participants",noTitle:"Specify a title",noStart:"Specify a start date",mon:"Mon",confirmRemoveTaskMessage:"Would you also like to remove the task from the task list?",week:"W"};
sv.i18n.portlet.social.calendar.calendar.fi={tuesday:"Tiistai",confirmRemoveMessage:"Oletko varma, ett\u00e4 haluat poistaa tapahtuman?",sat:"La",description:"Kuvaus",buttonTextWeek:"Viikko",allday:"Joka p\u00e4iv\u00e4",jun:"kes",jul:"hei",apr:"huh",create:"Luo tapahtuma",may:"tou",confirmRemoveTaskRemove:"Kyll\u00e4",titleDay:"dddd d MMM yyyy",mar:"maa",map:"Kartta",sunday:"Sunnuntai",columnWeek:"dddd d/MM",confirmRemoveTaskTitle:"Poista",axisFormat:"HH:mm",columnMonth:"ddd",eventState:"Status",
february:"Helmikuu",january:"Tammikuu",more:"Lue lis\u00e4\u00e4",wed:"Ke",jan:"tam",sep:"syy",event:"Tapahtuma",aug:"elo",buttonTextAgendaList:"Lista",filterMine:"Kaikki",monday:"Maanantai",filterAll:"Vain min\u00e4",april:"Huhtikuu",timeFormatAgenda:"HH:mm{ - HH:mm}",noOwner:"Lis\u00e4\u00e4 omistaja",createEvent:"Tapahtuma",titleWeek:"MMM d[, yyyy]{ -[ MMM] d, yyyy}",october:"Lokakuu",timeFormat:"HH:mm",name:"Nimi",noEnd:"Lis\u00e4\u00e4 p\u00e4\u00e4ttymisp\u00e4iv\u00e4",confirmRemoveTaskSaveInTasks:"Ei, s\u00e4ilyt\u00e4 listalla",
invalidAllDayTimePeriod:"P\u00e4\u00e4ttymisp\u00e4iv\u00e4n tulee olla sama tai j\u00e4lkeen aloitusp\u00e4iv\u00e4n",friday:"Perjantai",eventDetails:"Detaljit",invalidTimePeriod:"P\u00e4\u00e4ttymisajan tulee olla alkamisajan j\u00e4lkeen",wednesday:"Keskiviikko",november:"Marraskuu",titleMonth:"MMMM yyyy",june:"Kes\u00e4kuu",fri:"Pe",buttonTextDay:"P\u00e4iv\u00e4",owner:"Omistaja",task:"Toiminto",confirmRemoveTitle:"Poista",march:"Maaliskuu",saturday:"Lauantai",december:"Joulukuu",august:"Elokuu",
sun:"Su",september:"Syyskuu",oct:"lok",tue:"Ti",buttonTextToday:"T\u00e4n\u00e4\u00e4n",buttonTextMonth:"Kuukausi",thursday:"Torstai",thu:"To",feb:"hel",nov:"mar",july:"Hein\u00e4kuu",columnDay:"dddd d/MM",dec:"jou",participants:"Osanottaja",noTitle:"Lis\u00e4\u00e4 otsikko",noStart:"Lis\u00e4\u00e4 aloitusp\u00e4iv\u00e4",mon:"Ma",confirmRemoveTaskMessage:"Haluatko poistaa my\u00f6s listasta?",week:"Vko"};
sv.i18n.portlet.social.calendar.calendar.no={tuesday:"Tirsdag",confirmRemoveMessage:"Er du sikker p\u00e5 at du vil fjerne hendelsen?",sat:"L\u00f8r",description:"Beskrivelse",buttonTextWeek:"Uke",allday:"Heldag",jun:"jun",jul:"jul",apr:"apr",create:"Legg til hendelse",may:"Mai",confirmRemoveTaskRemove:"Ja",titleDay:"dddd d MMM yyyy",mar:"mar",map:"Kart",sunday:"S\u00f8ndag",columnWeek:"dddd d/MM",confirmRemoveTaskTitle:"Fjern",axisFormat:"HH:mm",columnMonth:"ddd",eventState:"Status",february:"Februar",
january:"Januar",more:"Les mer",wed:"Ons",jan:"jan",sep:"sep",event:"Hendelse",aug:"aug",buttonTextAgendaList:"Liste",filterMine:"Allas",monday:"Mandag",filterAll:"Bare mine",april:"April",timeFormatAgenda:"HH:mm{ - HH:mm}",noOwner:"Angi en eier",createEvent:"Hendelse",titleWeek:"d [MMM yyyy]{ - d MMM yyyy}",october:"Oktober",timeFormat:"HH:mm",name:"Tittel",noEnd:"Angi en sluttdato",confirmRemoveTaskSaveInTasks:"Nei, lagre i oppgavelisten",invalidAllDayTimePeriod:"Sluttdato m\u00e5 v\u00e6re samme eller etter startdato",
friday:"Fredag",eventDetails:"Detaljer",invalidTimePeriod:"Sluttid m\u00e5 v\u00e6re etter starttid",wednesday:"Onsdag",november:"November",titleMonth:"MMMM yyyy",june:"Juni",fri:"Fre",buttonTextDay:"Dag",owner:"Eier",task:"Opplysning",confirmRemoveTitle:"Fjern",march:"Mars",saturday:"L\u00f8rdag",december:"Desember",august:"August",sun:"S\u00f8n",september:"September",oct:"okt",tue:"Tir",buttonTextToday:"I dag",buttonTextMonth:"M\u00e5ned",thursday:"Torsdag",thu:"Tor",feb:"feb",nov:"nov",july:"Juli",
columnDay:"dddd d/MM",dec:"des",participants:"Deltager",noTitle:"Angi en tittel",noStart:"Angi en startdato",mon:"Man",confirmRemoveTaskMessage:"Vil du ogs\u00e5 fjerne opplysningen fra oppgavelisten?",week:"V"};
sv.i18n.portlet.social.calendar.calendar.sv={tuesday:"Tisdag",confirmRemoveMessage:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort h\u00e4ndelsen?",sat:"L\u00f6r",description:"Beskrivning",buttonTextWeek:"Vecka",allday:"Heldag",jun:"jun",jul:"jul",apr:"apr",create:"L\u00e4gg till h\u00e4ndelse",may:"Maj",confirmRemoveTaskRemove:"Ja",titleDay:"dddd d MMM yyyy",mar:"mar",map:"Karta",sunday:"S\u00f6ndag",columnWeek:"dddd d/MM",confirmRemoveTaskTitle:"Ta bort",axisFormat:"HH:mm",columnMonth:"ddd",
eventState:"Status",february:"Februari",january:"Januari",more:"L\u00e4s mer",wed:"Ons",jan:"jan",sep:"sep",event:"H\u00e4ndelse",aug:"aug",buttonTextAgendaList:"Lista",filterMine:"Allas",monday:"M\u00e5ndag",filterAll:"Endast mina",april:"April",timeFormatAgenda:"HH:mm{ - HH:mm}",noOwner:"Ange en \u00e4gare",createEvent:"H\u00e4ndelse",titleWeek:"d [MMM yyyy]{ - d MMM yyyy}",october:"Oktober",timeFormat:"HH:mm",name:"Titel",noEnd:"Ange ett slutdatum",confirmRemoveTaskSaveInTasks:"Nej, spara i uppgiftslistan",
invalidAllDayTimePeriod:"Slutdatum m\u00e5ste vara samma eller efter startdatum",friday:"Fredag",eventDetails:"Detaljer",invalidTimePeriod:"Sluttid m\u00e5ste vara efter starttid",wednesday:"Onsdag",november:"November",titleMonth:"MMMM yyyy",june:"Juni",fri:"Fre",buttonTextDay:"Dag",owner:"\u00c4gare",task:"Uppgift",confirmRemoveTitle:"Ta bort",march:"Mars",saturday:"L\u00f6rdag",december:"December",august:"Augusti",sun:"S\u00f6n",september:"September",oct:"okt",tue:"Tis",buttonTextToday:"Idag",buttonTextMonth:"M\u00e5nad",
thursday:"Torsdag",thu:"Tor",feb:"feb",nov:"nov",july:"Juli",columnDay:"dddd d/MM",dec:"dec",participants:"Deltagare",noTitle:"Ange en titel",noStart:"Ange ett startdatum",mon:"M\u00e5n",confirmRemoveTaskMessage:"Vill du \u00e4ven ta bort uppgiften fr\u00e5n uppgiftslistan?",week:"V"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.comments2=sv.i18n.portlet.comments2||{};sv.i18n.portlet.comments2.comments=sv.i18n.portlet.comments2.comments||{};sv.i18n.portlet.comments2.comments.de={};
sv.i18n.portlet.comments2.comments.en={removeCommentBody:"Are you sure you want to delete the comment?",commentToLongHeading:"Too long",removeCommentTitle:"Delete comment",showMore:"Show more",noNameBody:"No name given. Name is mandatory",showLess:"Show less",commentToLongBody:"The comment you where trying to post was too long.",moderatedHeading:"Moderated comments field",save:"Save",moderatedBody:"The comments function is moderated.\nYour comment will become visible only after a moderator has approved it.",
editCommentTitle:"Edit comment",hiddenComment:"Hidden comment",noNameHeading:"No name",postFailedHeading:"ERROR",postFailedBody:"An error has occurred, the comment was not published."};
sv.i18n.portlet.comments2.comments.fi={removeCommentBody:"Oletko varma, ett\u00e4 haluat poistaa kommentin?",commentToLongHeading:"Liian pitk\u00e4",removeCommentTitle:"Poista kommentti",showMore:"N\u00e4yt\u00e4 lis\u00e4\u00e4",noNameBody:"Nime\u00e4 ei annettu. Nimi on pakollinen",showLess:"N\u00e4yt\u00e4 v\u00e4hemm\u00e4n",commentToLongBody:"Yritit l\u00e4hett\u00e4\u00e4 liian pitk\u00e4n kommentin.",moderatedHeading:"Moderoitu kommenttikentt\u00e4",save:"Tallenna",moderatedBody:"Kommentointitoiminto on moderoitu.\nKommenttisi tulee n\u00e4kyviin, kun moderaattori on hyv\u00e4ksynyt sen.",
hiddenComment:"Poistunut kommentti",noNameHeading:"Ei nime\u00e4",postFailedHeading:"VIRHE",postFailedBody:"Tapahtui virhe, kommenttia ei julkaistu."};
sv.i18n.portlet.comments2.comments.no={removeCommentBody:"Er du sikker p\u00e5 at du vil fjerne kommentaren?",commentToLongHeading:"For lang",removeCommentTitle:"Fjern kommentar",showMore:"Vis mer",noNameBody:"Intet navn angitt. Navn er obligatorisk",Din:"kommentar blir synlig f\u00f8rst n\u00e5r en moderator har godkjent den.",showLess:"Vis mindre",moderatedHeading:"Moderert kommentarfelt",commentToLongBody:"Kommentaren du fors\u00f8kte \u00e5 sende, var for lang.",save:"Lagre",moderatedBody:"Kommentarfunksjonen er moderert.",
editCommentTitle:"Rediger kommentar",hiddenComment:"Skjult kommentar",noNameHeading:"Intet navn",postFailedHeading:"FEIL",postFailedBody:"Det oppsto en feil, kommentaren ble ikke publisert."};
sv.i18n.portlet.comments2.comments.sv={removeCommentBody:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort kommentaren?",commentToLongHeading:"F\u00f6r l\u00e5ng",removeCommentTitle:"Ta bort kommentar",showMore:"Visa mer",noNameBody:"Inget namn angivet. Namn \u00e4r obligatoriskt",showLess:"Visa mindre",commentToLongBody:"Kommentaren du f\u00f6rs\u00f6kte skicka var f\u00f6r l\u00e5ng.",moderatedHeading:"Modererat kommentarsf\u00e4lt",save:"Spara",moderatedBody:"Kommentarsfunktionen \u00e4r modererad.\nDin kommentar blir synlig f\u00f6rst n\u00e4r en moderator godk\u00e4nt den.",
editCommentTitle:"Redigera kommentar",hiddenComment:"Dold kommentar",noNameHeading:"Inget namn",postFailedHeading:"FEL",postFailedBody:"Ett fel har uppst\u00e5tt, kommentaren publicerades inte."};sv.i18n.common=sv.i18n.common||{};sv.i18n.common.de={help:"Hilfe",error:"Fehler",ok:"OK","new":"Neu",cancel:"K\u00fcndigen",save:"Spechern",close:"Schlie\u00dfen"};
sv.i18n.common.en={networkErrorText:"Information could not be updated. Could not contact server.",networkErrorTitle:"Communication with server failed",decimal:".",cancel:"Cancel",mins:"mins","error-fileExists":"{0} already exists.",ok:"OK","error-fileRenameHeading":"Could not rename file",add:"Add",close:"Close","new":"New",error:"Error","error-fileExistsHeading":"Could not add file",help:"Help",save:"Save",hrs:"hrs","error-unknown":"Unknown error.",remove:"Delete",hr:"hr"};
sv.i18n.common.fi={networkErrorText:"Aineistoa ei voitu p\u00e4ivitt\u00e4\u00e4. Palvelimeen ei saada yhteytt\u00e4.",networkErrorTitle:"Ongelma palvelinyhteydess\u00e4.",decimal:",",cancel:"Peruuta",mins:"min","error-fileExists":"{0} tiedosto on jo olemassa.",ok:"OK","error-fileRenameHeading":"Tiedoston nimen vaihto ei onnistunut",add:"Luo tili",close:"Sulje","new":"Uusi",error:"Virhe","error-fileExistsHeading":"Tiedoston lis\u00e4\u00e4minen ei onnistunut",help:"Ohje",save:"Tallenna",hrs:"tuntia",
"error-unknown":"Tuntematon virhe.",remove:"Poista",hr:"tunti"};
sv.i18n.common.no={networkErrorText:"Informasjonen kunne ikke oppdateres. Kunne ikke kontakte serveren.",networkErrorTitle:"Feil ved serverkommunikasjon",decimal:",",cancel:"Avbryt",mins:"min","error-fileExists":"{0} finnes allerede.",ok:"OK","error-fileRenameHeading":"Det var ikke mulig \u00e5 bytte navn p\u00e5 filen",add:"Legg til",close:"Lukk","new":"Ny",error:"Feil","error-fileExistsHeading":"Det var ikke mulig \u00e5 legge til filen",help:"Hjelp",save:"Lagre",hrs:"time","error-unknown":"Ukjent feil.",
remove:"Fjern",hr:"time"};
sv.i18n.common.sv={networkErrorText:"Informationen kunde inte uppdateras. Kunde inte kontakta servern.",networkErrorTitle:"Fel vid serverkommunikation",decimal:",",cancel:"Avbryt",mins:"min","error-fileExists":"{0} finns redan.",ok:"OK","error-fileRenameHeading":"Det gick inte att byta namn p\u00e5 filen",add:"L\u00e4gg till",close:"St\u00e4ng","new":"Ny",error:"Fel","error-fileExistsHeading":"Det gick inte att l\u00e4gga till filen",help:"Hj\u00e4lp",save:"Spara",hrs:"tim","error-unknown":"Ok\u00e4nt fel.",
remove:"Ta bort",hr:"tim"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.contactsearch=sv.i18n.portlet.social.contactsearch||{};sv.i18n.portlet.social.contactsearch.contactsearch=sv.i18n.portlet.social.contactsearch.contactsearch||{};sv.i18n.portlet.social.contactsearch.contactsearch.de={};sv.i18n.portlet.social.contactsearch.contactsearch.en={showList:"Show in list \u00bb",showAll:"Show all \u00bb",noHits:"Your search generated no hits"};
sv.i18n.portlet.social.contactsearch.contactsearch.fi={showList:"N\u00e4yt\u00e4 listalla \u00bb",showAll:"N\u00e4yt\u00e4 kaikki henkil\u00f6t \u00bb",noHits:"Haku ei tuottanut tuloksia"};sv.i18n.portlet.social.contactsearch.contactsearch.no={showList:"Vis i liste \u00bb",showAll:"Vis flere personer \u00bb",noHits:"S\u00f8ket ga ingen treff"};sv.i18n.portlet.social.contactsearch.contactsearch.sv={showList:"Visa i lista \u00bb",showAll:"Visa fler personer \u00bb",noHits:"Din s\u00f6kning gav inga tr\u00e4ffar"};
sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.createdocument=sv.i18n.portlet.social.createdocument||{};sv.i18n.portlet.social.createdocument.createdocument=sv.i18n.portlet.social.createdocument.createdocument||{};sv.i18n.portlet.social.createdocument.createdocument.de={};sv.i18n.portlet.social.createdocument.createdocument.en={location:"Location",name:"Name",tags:"Tags",create:"Create",cancel:"Cancel",createDocumentTitle:"Create document"};
sv.i18n.portlet.social.createdocument.createdocument.fi={};sv.i18n.portlet.social.createdocument.createdocument.no={location:"Plass",name:"Navn",tags:"Etiketter",create:"Opprett",cancel:"Avbryt",createDocumentTitle:"Opprett dokument"};sv.i18n.portlet.social.createdocument.createdocument.sv={location:"Plats",name:"Namn",tags:"Etiketter",create:"Skapa",cancel:"Avbryt",createDocumentTitle:"Skapa dokument"};sv.i18n.util=sv.i18n.util||{};sv.i18n.util.dialogutil=sv.i18n.util.dialogutil||{};
sv.i18n.util.dialogutil.de={};sv.i18n.util.dialogutil.en={ok:"OK",cancel:"Cancel"};sv.i18n.util.dialogutil.fi={ok:"OK",cancel:"Peruuta"};sv.i18n.util.dialogutil.no={ok:"OK",cancel:"Avbryt"};sv.i18n.util.dialogutil.sv={ok:"OK",cancel:"Avbryt"};sv.i18n.util=sv.i18n.util||{};sv.i18n.util.errorutil=sv.i18n.util.errorutil||{};sv.i18n.util.errorutil.de={};
sv.i18n.util.errorutil.en={errorMessage:"A problem occurred that prevented the task from being performed ({0})",connectionErrorMessageTitle:"Connection error",errorMessageTitle:"An error occurred",connectionErrorMessage:"Could not connect to the server, please try again later"};sv.i18n.util.errorutil.fi={errorMessage:"Toimintoa ei voitu virheen takia suorittaa pyydetyll\u00e4 tavalla ({0})",connectionErrorMessageTitle:"Yhteysongelma",errorMessageTitle:"Tapahtui virhe",connectionErrorMessage:"Palvelimeen ei saatu yhteytt\u00e4, kokeile my\u00f6hemmin uudelleen"};
sv.i18n.util.errorutil.no={errorMessage:"Det oppsto et problem som gjorde at opplysningen ikke kunne utf\u00f8res slik det var tenkt ({0})",connectionErrorMessageTitle:"Tilkoblingsproblem",errorMessageTitle:"Det oppsto en feil",connectionErrorMessage:"Kunne ikke koble til serveren, pr\u00f8v igjen senere"};
sv.i18n.util.errorutil.sv={errorMessage:"Ett problem uppstod som gjorde att uppgiften inte kunde utf\u00f6ras som det var t\u00e4nkt ({0})",connectionErrorMessageTitle:"Anslutningsproblem",errorMessageTitle:"Ett fel intr\u00e4ffade",connectionErrorMessage:"Kunde inte ansluta till servern, var god f\u00f6rs\u00f6k igen senare"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.fileview=sv.i18n.portlet.social.fileview||{};
sv.i18n.portlet.social.fileview.file=sv.i18n.portlet.social.fileview.file||{};sv.i18n.portlet.social.fileview.file.de={};
sv.i18n.portlet.social.fileview.file.en={emptyDescription:"No description",showLess:"Show less",versionDescriptionTitle:"Description",download:"Download",versionDescriptionMsg:"Description",disableVersioning:"Are you sure you want to disable versioning? All previous versions will be deleted!",shareEntry:"Share timeline post",removeCommentBody:"Are you sure you want to delete the comment?",emptyText:"No value",sharedMessageContent:"Message is now shared to your followers",removeCommentTitle:"Delete comment",
unLockMessage:"The file is now unlocked",lockErrorMessage:"File already locked by {0}",renameFileTitle:"Rename",unlockErrorMessage:"File locked by {0}",commentToLongHeading:"Too long",renameFileMessage:"Name",lockMessage:"File locked by {0}",sharedMessageTitle:"Shared message",share:"Share",shareComment:"Add comment",editCommentTitle:"Edit comment",save:"Save",commentToLongBody:"The comment you where trying to post was too long.",showMore:"Show more",removeFile:"Are you sure you want to delete this file?",
removeVersion:"Are you sure you want to delete this file version?",versioning:"Versioning",remove:"Delete",name:"Name"};
sv.i18n.portlet.social.fileview.file.fi={emptyDescription:"Ei kuvausta",showLess:"N\u00e4yt\u00e4 v\u00e4hemm\u00e4n",versionDescriptionTitle:"Kuvaus",download:"Lataa",versionDescriptionMsg:"Kuvaus",disableVersioning:"Oletko varma, ett\u00e4 haluat lopettaa versioinnin? Kaikki vanhat versiot poistuvat.",shareEntry:"Jaa sis\u00e4lt\u00f6",removeCommentBody:"Oletko varma, ett\u00e4 haluat poistaa kommentin?",emptyText:"Ei sis\u00e4lt\u00f6\u00e4",sharedMessageContent:"Viesti on nyt jaettu sein\u00e4ll\u00e4si",
removeCommentTitle:"Poista kommentti",unLockMessage:"Tiedosto on nyt vapautettu",lockErrorMessage:"Tiedosto on lukittu {0}",renameFileTitle:"Vaihda nimi",unlockErrorMessage:"Tiedosto on vapautettu {0}",commentToLongHeading:"Liian pitk\u00e4",renameFileMessage:"Nimi",lockMessage:"Tiedosto on nyt lukittu {0}",sharedMessageTitle:"Jaettu viesti",share:"Jaa",shareComment:"Jaa kommentti",commentToLongBody:"Kommentti, jota yritit l\u00e4hett\u00e4\u00e4, on liian pitk\u00e4.",showMore:"N\u00e4yt\u00e4 lis\u00e4\u00e4",
removeFile:"Oletko varma, ett\u00e4 haluat poistaa tiedoston?",removeVersion:"Oletko varma, ett\u00e4 haluat poistaa t\u00e4m\u00e4nhetkisen version tiedostosta?",versioning:"Versiointi",remove:"Poista",name:"Nimi"};
sv.i18n.portlet.social.fileview.file.no={emptyDescription:"Ingen beskrivelse",showLess:"Vis mindre",versionDescriptionTitle:"Beskrivelse",download:"Last ned",versionDescriptionMsg:"Beskrivelse",disableVersioning:"Er du sikker p\u00e5 at du vil sl\u00e5 av versjonering, alle gamle versjoner kommer til \u00e5 forsvinne?",shareEntry:"Del innlegg",removeCommentBody:"Er du sikker p\u00e5 at du vil fjerne kommentaren?",emptyText:"Ingen verdi",sharedMessageContent:"Meldingen er n\u00e5 delt i din flyt",
removeCommentTitle:"Fjern kommentar",unLockMessage:"Filen er n\u00e5 oppl\u00e5st",lockErrorMessage:"Filen er allerede l\u00e5st av {0}",renameFileTitle:"Bytt navn",unlockErrorMessage:"Filen er l\u00e5st av {0}",commentToLongHeading:"For lang",renameFileMessage:"Navn",lockMessage:"Filen er n\u00e5 l\u00e5st av {0}",sharedMessageTitle:"Delt melding",share:"Del",shareComment:"Legg til kommentar",editCommentTitle:"Rediger kommentar",save:"Lagre",commentToLongBody:"Kommentaren du fors\u00f8kte \u00e5 sende, var for lang.",
showMore:"Vis mer",removeFile:"Er du sikker p\u00e5 at du vil fjerne aktuell fil?",removeVersion:"Er du sikker p\u00e5 at du vil fjerne aktuell versjon av filen?",versioning:"Versjonering",remove:"Fjern",name:"Navn"};
sv.i18n.portlet.social.fileview.file.sv={emptyDescription:"Ingen beskrivning",showLess:"Visa mindre",versionDescriptionTitle:"Beskrivning",download:"Ladda ner",versionDescriptionMsg:"Beskrivning",disableVersioning:"\u00c4r du s\u00e4ker p\u00e5 att du vill sl\u00e5 av versionering, alla gamla verisoner kommer att f\u00f6rsvinna?",shareEntry:"Dela inl\u00e4gg",removeCommentBody:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort kommentaren?",emptyText:"Inget v\u00e4rde",sharedMessageContent:"Meddelandet \u00e4r nu delat i ditt fl\u00f6de",
removeCommentTitle:"Ta bort kommentar",unLockMessage:"Filen \u00e4r nu uppl\u00e5st",lockErrorMessage:"Filen \u00e4r redan l\u00e5st av {0}",renameFileTitle:"Byt namn",unlockErrorMessage:"Filen \u00e4r l\u00e5st av {0}",commentToLongHeading:"F\u00f6r l\u00e5ng",renameFileMessage:"Namn",lockMessage:"Filen \u00e4r nu l\u00e5st av {0}",sharedMessageTitle:"Delat meddelande",share:"Dela",shareComment:"L\u00e4gg till kommentar",editCommentTitle:"Redigera kommentar",save:"Spara",commentToLongBody:"Kommentaren du f\u00f6rs\u00f6kte skicka var f\u00f6r l\u00e5ng.",
showMore:"Visa mer",removeFile:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort aktuell fil?",removeVersion:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort aktuell version av filen?",versioning:"Versionering",remove:"Ta bort",name:"Namn"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.filelist=sv.i18n.portlet.social.filelist||{};sv.i18n.portlet.social.filelist.filelist=sv.i18n.portlet.social.filelist.filelist||{};
sv.i18n.portlet.social.filelist.filelist.de={};sv.i18n.portlet.social.filelist.filelist.en={showAllFiles:"Show all files ({0})"};sv.i18n.portlet.social.filelist.filelist.fi={showAllFiles:"N\u00e4yt\u00e4 kaikki tiedostot ({0})"};sv.i18n.portlet.social.filelist.filelist.no={showAllFiles:"Vis alle filer ({0})"};sv.i18n.portlet.social.filelist.filelist.sv={showAllFiles:"Visa alla filer ({0})"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};
sv.i18n.portlet.social.groupadminall=sv.i18n.portlet.social.groupadminall||{};sv.i18n.portlet.social.groupadminall.groupadminall=sv.i18n.portlet.social.groupadminall.groupadminall||{};sv.i18n.portlet.social.groupadminall.groupadminall.de={};sv.i18n.portlet.social.groupadminall.groupadminall.en={successAddAdminMessage:"{0} is now an administrator",searchUser:"Search user",successMessage:"{0} is no longer a member of the group",successAddMessageTitle:"Info",successAddMessage:"{0} is now a member of the group"};
sv.i18n.portlet.social.groupadminall.groupadminall.fi={successAddAdminMessage:"{0} on nyt moderaattori",searchUser:"Hae henkil\u00f6\u00e4",successMessage:"{0} on nyt poistettu ryhm\u00e4st\u00e4",successAddMessageTitle:"Informaatio",successAddMessage:"{0} on nyt ryhm\u00e4n j\u00e4sen"};
sv.i18n.portlet.social.groupadminall.groupadminall.no={successAddAdminMessage:"{0} er n\u00e5 adminstrator",searchUser:"S\u00f8k person",successMessage:"{0} er n\u00e5 fjernet fra gruppen",successAddMessageTitle:"Info",successAddMessage:"{0} er n\u00e5 medlem av gruppen"};sv.i18n.portlet.social.groupadminall.groupadminall.sv={successAddAdminMessage:"{0} \u00e4r nu adminstrat\u00f6r",searchUser:"S\u00f6k person",successMessage:"{0} \u00e4r nu borttagen ur gruppen",successAddMessageTitle:"Info",successAddMessage:"{0} \u00e4r nu medlem i gruppen"};
sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.grouptypeselector=sv.i18n.portlet.social.grouptypeselector||{};sv.i18n.portlet.social.grouptypeselector.grouptypeselector=sv.i18n.portlet.social.grouptypeselector.grouptypeselector||{};sv.i18n.portlet.social.grouptypeselector.grouptypeselector.de={};
sv.i18n.portlet.social.grouptypeselector.grouptypeselector.en={searchUser:"Search administrator",unpublishGroupBody:"Are you sure that you want to delete this group?",groupAlreadyExists:"A group with the same already exists",errorTitle:"Error",unpublishGroupTitle:"Delete group","group-settingsLabel":"Group settings"};
sv.i18n.portlet.social.grouptypeselector.grouptypeselector.fi={searchUser:"Etsi moderaattoria",groupAlreadyExists:"T\u00e4m\u00e4n niminen ryhm\u00e4 on jo olemassa",errorTitle:"Virhe","group-settingsLabel":"Ryhm\u00e4n asetukset"};
sv.i18n.portlet.social.grouptypeselector.grouptypeselector.no={searchUser:"S\u00f8k administrator",unpublishGroupBody:"Er du sikker p\u00e5 at du vil fjerne denne gruppen?",groupAlreadyExists:"Det finnes allerede en gruppe med samme navn",errorTitle:"Feil",unpublishGroupTitle:"Fjern gruppe","group-settingsLabel":"Gruppeinnstillinger"};
sv.i18n.portlet.social.grouptypeselector.grouptypeselector.sv={searchUser:"S\u00f6k administrat\u00f6r",unpublishGroupBody:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort denna grupp?",groupAlreadyExists:"En grupp med samma namn finns redan",errorTitle:"Fel",unpublishGroupTitle:"Ta bort grupp","group-settingsLabel":"Gruppinst\u00e4llningar"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.util=sv.i18n.portlet.util||{};sv.i18n.portlet.util.likableutil=sv.i18n.portlet.util.likableutil||{};
sv.i18n.portlet.util.likableutil.de={};sv.i18n.portlet.util.likableutil.en={likes:"Likes",like:"Like"};sv.i18n.portlet.util.likableutil.fi={likes:"Tykk\u00e4\u00e4",like:"Tykk\u00e4ys"};sv.i18n.portlet.util.likableutil.no={likes:"Liker",like:"Lik"};sv.i18n.portlet.util.likableutil.sv={likes:"Gillar",like:"Gilla"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.messages=sv.i18n.portlet.social.messages||{};
sv.i18n.portlet.social.messages.messages=sv.i18n.portlet.social.messages.messages||{};sv.i18n.portlet.social.messages.messages.de={};sv.i18n.portlet.social.messages.messages.en={newMember:"New chat member",newMessage:"New message...",participants:"Add recipients...",typing:"is typing...",conversations:"Inbox",placeholder:"Write your message here...",showMore:"Show more conversations"};
sv.i18n.portlet.social.messages.messages.fi={newMember:"Uusi viesti keskustelussa",participants:"L\u00e4het\u00e4 vastaanottajalle...",typing:"kirjoittaa...",conversations:"Postilaatikko",placeholder:"Kirjoita viestisi t\u00e4h\u00e4n...",showMore:"N\u00e4yt\u00e4 lis\u00e4\u00e4"};
sv.i18n.portlet.social.messages.messages.no={newMember:"Nytt medlem i chatten",newMessage:"Ny melding ...",participants:"Legg til mottager ...",typing:"skriver ...",conversations:"Innboks",placeholder:"Skriv din melding her ...",showMore:"Vis flere samtaler"};
sv.i18n.portlet.social.messages.messages.sv={newMember:"Ny medlem i chatten",newMessage:"Nytt meddelande...",participants:"L\u00e4gg till mottagare...",typing:"skriver...",conversations:"Inkorg",placeholder:"Skriv ditt meddelande h\u00e4r...",showMore:"Visa fler konversationer"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.notifications=sv.i18n.portlet.social.notifications||{};
sv.i18n.portlet.social.notifications.notifications=sv.i18n.portlet.social.notifications.notifications||{};sv.i18n.portlet.social.notifications.notifications.de={};sv.i18n.portlet.social.notifications.notifications.en={"error-unknown":"Unable to read notifications",notifications:"Notifications",showMore:"Show more notifications"};sv.i18n.portlet.social.notifications.notifications.fi={"error-unknown":"Luku ep\u00e4onnistui",notifications:"Merkinn\u00e4t",showMore:"N\u00e4yt\u00e4 lis\u00e4\u00e4 merkint\u00f6j\u00e4"};
sv.i18n.portlet.social.notifications.notifications.no={"error-unknown":"Kunne ikke lese inn varsler",notifications:"Varsler",showMore:"Vis flere varsler"};sv.i18n.portlet.social.notifications.notifications.sv={"error-unknown":"Kunde inte l\u00e4sa in notifieringar",notifications:"Notifieringar",showMore:"Visa fler notifieringar"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.util=sv.i18n.portlet.util||{};sv.i18n.portlet.util.oembed=sv.i18n.portlet.util.oembed||{};
sv.i18n.portlet.util.oembed.de={};sv.i18n.portlet.util.oembed.en={contentNotFound:"No content found for URL:"};sv.i18n.portlet.util.oembed.fi={};sv.i18n.portlet.util.oembed.no={contentNotFound:"Ikke noe innhold ble funnet for adresse:"};sv.i18n.portlet.util.oembed.sv={contentNotFound:"Inget inneh\u00e5ll hittades f\u00f6r adress:"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};
sv.i18n.portlet.social.personalsettings=sv.i18n.portlet.social.personalsettings||{};sv.i18n.portlet.social.personalsettings.personalsettings=sv.i18n.portlet.social.personalsettings.personalsettings||{};sv.i18n.portlet.social.personalsettings.personalsettings.de={};
sv.i18n.portlet.social.personalsettings.personalsettings.en={"personalsettings-notificationsLabel":"Notification settings","personalsettings-generalLabel":"General settings","personalsettings-notificationsHelp":"Send email notifications when:",networkErrorTitle:"Communication with server failed",networkErrorText:"Information could not be updated. Could not contact server.","personalsettings-push-notificationsLabel":"Notification settings"};
sv.i18n.portlet.social.personalsettings.personalsettings.fi={"personalsettings-notificationsLabel":"Merkint\u00f6jen asetukset","personalsettings-generalLabel":"Yleiset asetukset","personalsettings-notificationsHelp":"L\u00e4het\u00e4 ilmoitus s\u00e4hk\u00f6postilla, kun:",networkErrorTitle:"Ongelma palvelinyhteydess\u00e4",networkErrorText:"Informaatiota ei voitu p\u00e4ivitt\u00e4\u00e4. Palvelimeen ei saada yhteytt\u00e4."};
sv.i18n.portlet.social.personalsettings.personalsettings.no={"personalsettings-notificationsLabel":"Varselinnstillinger","personalsettings-generalLabel":"Generelle innstillinger","personalsettings-notificationsHelp":"Send varsler via e-post n\u00e5r:",networkErrorTitle:"Feil ved serverkommunikasjon",networkErrorText:"Informasjonen kunne ikke oppdateres. Kunne ikke kontakte serveren.","personalsettings-push-notificationsLabel":"Varselinnstillinger"};
sv.i18n.portlet.social.personalsettings.personalsettings.sv={"personalsettings-notificationsLabel":"Notifieringsinst\u00e4llningar","personalsettings-generalLabel":"Allm\u00e4nna inst\u00e4llningar","personalsettings-notificationsHelp":"Skicka notifieringar via e-post n\u00e4r:",networkErrorTitle:"Fel vid serverkommunikation",networkErrorText:"Informationen kunde inte uppdateras. Kunde inte kontakta servern.","personalsettings-push-notificationsLabel":"Notifieringsinst\u00e4llningar"};
sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.profileimage=sv.i18n.portlet.social.profileimage||{};sv.i18n.portlet.social.profileimage.profileimage=sv.i18n.portlet.social.profileimage.profileimage||{};sv.i18n.portlet.social.profileimage.profileimage.de={};
sv.i18n.portlet.social.profileimage.profileimage.en={"error-dimension":"The image is too small. The minimum size is {0} x {1} pixels","crop-title":"Crop the image","error-unknown":"Unable to upload image","error-size":"The image is too big. Maximum size is {0}MB","error-type":"Invalid file type {0}. Only image files are permitted (jpg, png and gif)"};
sv.i18n.portlet.social.profileimage.profileimage.fi={"error-dimension":"Kuva on liian pieni. V\u00e4himm\u00e4istiedostokoko on {0} x {1} pikseli\u00e4","crop-title":"Rajaa kuvaa","error-unknown":"Kuvaa ei voitu ladata","error-size":"Kuva on liian suuri. Maksimi tiedostokoko on {0}MB","error-type":"V\u00e4\u00e4r\u00e4 tiedostomuoto {0}. Vain kuvat hyv\u00e4ksyt\u00e4\u00e4n (jpg, png ja gif)"};
sv.i18n.portlet.social.profileimage.profileimage.no={"error-dimension":"Bildet er for lite. Min. st\u00f8rrelse er {0} x {1} piksler","crop-title":"Beskj\u00e6r bildet","error-unknown":"Kunne ikke laste opp bildet","error-size":"Bildet er for stort. Maks. st\u00f8rrelse er {0}MB","error-type":"Feil filtype {0}. Bare bilder tillates (jpg, png og gif)"};
sv.i18n.portlet.social.profileimage.profileimage.sv={"error-dimension":"Bilden \u00e4r f\u00f6r liten. Minimal storlek \u00e4r {0} x {1} pixlar","crop-title":"Besk\u00e4r bilden","error-unknown":"Kunde inte ladda upp bilden","error-size":"Bilden \u00e4r f\u00f6r stor. Maximal storlek \u00e4r {0}MB","error-type":"Felaktig filtyp {0}. Endast bilder till\u00e5ts (jpg, png and gif)"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};
sv.i18n.portlet.social.profileprogress=sv.i18n.portlet.social.profileprogress||{};sv.i18n.portlet.social.profileprogress.profileprogress=sv.i18n.portlet.social.profileprogress.profileprogress||{};sv.i18n.portlet.social.profileprogress.profileprogress.de={};
sv.i18n.portlet.social.profileprogress.profileprogress.en={missingValue:"Missing value",userFields:"User fields",oneEntry:"At least one post in timeline",hasContact:"At least one contact",inGroup:"Member of at least one group",helpPage:"Help page",hasProfileImage:"Personal profile image",collaborationCriteria:"Collaboration criteria",profileCriteria:"Profile criteria",incomplete:"Not met",profileProgress:"Profile progress"};
sv.i18n.portlet.social.profileprogress.profileprogress.fi={missingValue:"Arvo puuttuu",userFields:"K\u00e4ytt\u00e4j\u00e4kentt\u00e4",oneEntry:"V\u00e4hint\u00e4\u00e4n yksi merkint\u00e4 sein\u00e4ll\u00e4",hasContact:"V\u00e4hint\u00e4\u00e4n yksi yhteystieto",inGroup:"J\u00e4sen v\u00e4hint\u00e4\u00e4n yhdess\u00e4 ryhm\u00e4ss\u00e4",helpPage:"Tukisivu",hasProfileImage:"Oma profilikuva",collaborationCriteria:"Ryhm\u00e4kriteerit",profileCriteria:"Profiilikriteerit",incomplete:"Ei lis\u00e4tty"};
sv.i18n.portlet.social.profileprogress.profileprogress.no={missingValue:"Mangler verdi",userFields:"Brukerfelt",oneEntry:"Minst ett innlegg i aktivitetsflyten",hasContact:"Minst \u00e9n kontakt",inGroup:"Medlem av minst \u00e9n gruppe",helpPage:"Hjelpeside",hasProfileImage:"Eget profilbilde",collaborationCriteria:"Samarbeidskriterier",profileCriteria:"Profilkriterier",incomplete:"Ikke oppfylt",profileProgress:"Profilstyrke"};
sv.i18n.portlet.social.profileprogress.profileprogress.sv={missingValue:"Saknar v\u00e4rde",userFields:"Anv\u00e4ndarf\u00e4lt",oneEntry:"Minst ett inl\u00e4gg i aktivitetsfl\u00f6det",hasContact:"Minst en kontakt",inGroup:"Medlem i minst en grupp",helpPage:"Hj\u00e4lpsida",hasProfileImage:"Egen profilbild",collaborationCriteria:"Samarbetskriterer",profileCriteria:"Profilkriterier",incomplete:"Ej uppfyllt",profileProgress:"Profilstyrka"};sv.i18n.portlet=sv.i18n.portlet||{};
sv.i18n.portlet.search=sv.i18n.portlet.search||{};sv.i18n.portlet.search.searchform2=sv.i18n.portlet.search.searchform2||{};sv.i18n.portlet.search.searchform2.searchform2=sv.i18n.portlet.search.searchform2.searchform2||{};sv.i18n.portlet.search.searchform2.searchform2.de={};sv.i18n.portlet.search.searchform2.searchform2.en={searchFailed:"Search failed with error code {0}."};sv.i18n.portlet.search.searchform2.searchform2.fi={searchFailed:"Haku ep\u00e4onnistui, virhekoodi {0}."};
sv.i18n.portlet.search.searchform2.searchform2.no={searchFailed:"S\u00f8ket mislyktes med feilkode {0}."};sv.i18n.portlet.search.searchform2.searchform2.sv={searchFailed:"S\u00f6kningen misslyckades med felkod {0}."};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.util=sv.i18n.portlet.util||{};sv.i18n.portlet.util.searchuserutil=sv.i18n.portlet.util.searchuserutil||{};sv.i18n.portlet.util.searchuserutil.de={};sv.i18n.portlet.util.searchuserutil.en={showAsList:"Show in list \u00bb",showAll:"Show all \u00bb"};
sv.i18n.portlet.util.searchuserutil.fi={showAsList:"N\u00e4yt\u00e4 listana \u00bb",showAll:"N\u00e4yt\u00e4 kaikki hakutulokset \u00bb"};sv.i18n.portlet.util.searchuserutil.no={showAsList:"Vis i liste \u00bb",showAll:"Vis alle s\u00f8ketreff \u00bb"};sv.i18n.portlet.util.searchuserutil.sv={showAsList:"Visa i lista \u00bb",showAll:"Visa alla s\u00f6ktr\u00e4ffar \u00bb"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};
sv.i18n.portlet.social.sharedlinks=sv.i18n.portlet.social.sharedlinks||{};sv.i18n.portlet.social.sharedlinks.sharedlinks=sv.i18n.portlet.social.sharedlinks.sharedlinks||{};sv.i18n.portlet.social.sharedlinks.sharedlinks.de={};
sv.i18n.portlet.social.sharedlinks.sharedlinks.en={placeholderUrl:"http://www.example.com",createdSharedLink:"Share a link",urlIsNotALink:"Invalid address",editSharedLink:"Edit a link",titleRequired:"Title required",save:"Save",removeLink:"Remove link",title:"Title",address:"Address",removeShareLink:"Are you sure that you want to delete the link?",share:"Share",addressRequired:"Address required"};sv.i18n.portlet.social.sharedlinks.sharedlinks.fi={};
sv.i18n.portlet.social.sharedlinks.sharedlinks.no={placeholderUrl:"http://www.eksempel.no",createdSharedLink:"Del en lenke",urlIsNotALink:"Ugyldig adresse",editSharedLink:"Rediger en lenke",titleRequired:"Det m\u00e5 angis en tittel",save:"Lagre",removeLink:"Fjern lenke",title:"Tittel",address:"Adresse",removeShareLink:"Er du sikker p\u00e5 at du vil fjerne lenken?",share:"Del",addressRequired:"Det m\u00e5 angis en adresse"};
sv.i18n.portlet.social.sharedlinks.sharedlinks.sv={placeholderUrl:"http://www.exempel.se",createdSharedLink:"Dela en l\u00e4nk",urlIsNotALink:"Ogiltig adress",editSharedLink:"Redigera en l\u00e4nk",titleRequired:"Titel m\u00e5ste anges",save:"Spara",removeLink:"Ta bort l\u00e4nk",title:"Titel",address:"Adress",removeShareLink:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort l\u00e4nken?",share:"Dela",addressRequired:"Adress m\u00e5ste anges"};sv.i18n.portlet=sv.i18n.portlet||{};
sv.i18n.portlet.sharepoint=sv.i18n.portlet.sharepoint||{};sv.i18n.portlet.sharepoint.sharepointfile=sv.i18n.portlet.sharepoint.sharepointfile||{};sv.i18n.portlet.sharepoint.sharepointfile.de={};sv.i18n.portlet.sharepoint.sharepointfile.en={loginButton:"Log in",connectToSharePoint:"Connect to SharePoint"};sv.i18n.portlet.sharepoint.sharepointfile.fi={};sv.i18n.portlet.sharepoint.sharepointfile.no={loginButton:"Logg inn",connectToSharePoint:"Koble til SharePoint"};
sv.i18n.portlet.sharepoint.sharepointfile.sv={loginButton:"Logga in",connectToSharePoint:"Anslut till SharePoint"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.taglist=sv.i18n.portlet.social.taglist||{};sv.i18n.portlet.social.taglist.taglist=sv.i18n.portlet.social.taglist.taglist||{};sv.i18n.portlet.social.taglist.taglist.de={};
sv.i18n.portlet.social.taglist.taglist.en={addDialogLabel:"Tag:",removedMessage:"The tag {0} was removed.",addDialogTitle:"Add tag"};sv.i18n.portlet.social.taglist.taglist.fi={addDialogLabel:"Risuaita:",removedMessage:"Risuaita {0} on poistettu.",addDialogTitle:"Lis\u00e4\u00e4 risuaita"};sv.i18n.portlet.social.taglist.taglist.no={addDialogLabel:"Etikett:",removedMessage:"Etiketten {0} er fjernet.",addDialogTitle:"Legg til etikett"};
sv.i18n.portlet.social.taglist.taglist.sv={addDialogLabel:"Etikett:",removedMessage:"Etiketten {0} har tagits bort.",addDialogTitle:"L\u00e4gg till etikett"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.tasks=sv.i18n.portlet.social.tasks||{};sv.i18n.portlet.social.tasks.tasks=sv.i18n.portlet.social.tasks.tasks||{};sv.i18n.portlet.social.tasks.tasks.de={};
sv.i18n.portlet.social.tasks.tasks.en={owner:"Owner",participants:"Participants",more:"More",noTitle:"Specify a title",confirmRemoveMessage:"Are you sure you want to delete the task?",noOwner:"Specify an owner",confirmRemoveCalendarSaveInCalendar:"No, save in the calendar",invalidAllDayTimePeriod:"End date must be the same or after start date",filter:"Show",noStart:"Specify a start date",confirmRemoveCalendarMessage:"Would you also like to delete the task from the calendar?",isDone:"is done",confirmRemoveCalendarTitle:"Delete",
confirmRemoveTitle:"Delete",task:"Task",doneText:"{0} of {1} are completed",confirmRemoveCalendarRemove:"Yes",noEnd:"Specify an end date",map:"Map",invalidTimePeriod:"End time must be after start time"};
sv.i18n.portlet.social.tasks.tasks.fi={owner:"Omistaja",participants:"Osanottajat",more:"Lue lis\u00e4\u00e4",noTitle:"Anna nimi",confirmRemoveMessage:"Oletko varma, ett\u00e4 haluat poistaa merkinn\u00e4t?",noOwner:"Sy\u00f6t\u00e4 omistaja",confirmRemoveCalendarSaveInCalendar:"Ei, s\u00e4ilyt\u00e4 kalenterissa",invalidAllDayTimePeriod:"P\u00e4\u00e4ttymisajan pit\u00e4\u00e4 olla sama tai j\u00e4lkeen aloitusajan",filter:"N\u00e4yt\u00e4",noStart:"Sy\u00f6t\u00e4 aloitusp\u00e4iv\u00e4",confirmRemoveCalendarMessage:"Haluatko poistaa merkinn\u00e4n my\u00f6s kalenterista?",
isDone:"on tehty",confirmRemoveCalendarTitle:"Poista",confirmRemoveTitle:"Poista",task:"Teht\u00e4v\u00e4",doneText:"{0} {1} :st\u00e4 on valmis",confirmRemoveCalendarRemove:"Kyll\u00e4",noEnd:"Sy\u00f6t\u00e4 p\u00e4\u00e4ttymisp\u00e4iv\u00e4",map:"Kartta",invalidTimePeriod:"Lopetusajan pit\u00e4\u00e4 olla aloitusajan j\u00e4lkeen"};
sv.i18n.portlet.social.tasks.tasks.no={owner:"Eier",participants:"Deltager",more:"Les mer",noTitle:"Angi en tittel",confirmRemoveMessage:"Er du sikker p\u00e5 at du vil fjerne opplysningen?",noOwner:"Angi en eier",confirmRemoveCalendarSaveInCalendar:"Nei, lagre i kalenderen",invalidAllDayTimePeriod:"Sluttdato m\u00e5 v\u00e6re samme eller etter startdato",filter:"Vis",noStart:"Angi en startdato",confirmRemoveCalendarMessage:"Vil du ogs\u00e5 fjerne opplysningen fra kalenderen?",isDone:"er klar",confirmRemoveCalendarTitle:"Fjern",
confirmRemoveTitle:"Fjern",task:"Opplysning",doneText:"{0} av {1} er utf\u00f8rt",confirmRemoveCalendarRemove:"Ja",noEnd:"Angi en sluttdato",map:"Kart",invalidTimePeriod:"Sluttid m\u00e5 v\u00e6re etter starttid"};
sv.i18n.portlet.social.tasks.tasks.sv={owner:"\u00c4gare",participants:"Deltagare",more:"L\u00e4s mer",noTitle:"Ange en titel",confirmRemoveMessage:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort uppgiften?",noOwner:"Ange en \u00e4gare",confirmRemoveCalendarSaveInCalendar:"Nej, spara i kalendern",invalidAllDayTimePeriod:"Slutdatum m\u00e5ste vara samma eller efter startdatum",filter:"Visa",noStart:"Ange ett startdatum",confirmRemoveCalendarMessage:"Vill du \u00e4ven ta bort uppgiften fr\u00e5n kalendern?",
isDone:"\u00e4r klara",confirmRemoveCalendarTitle:"Ta bort",confirmRemoveTitle:"Ta bort",task:"Uppgift",doneText:"{0} av {1} \u00e4r utf\u00f6rda",confirmRemoveCalendarRemove:"Ja",noEnd:"Ange ett slutdatum",map:"Karta",invalidTimePeriod:"Sluttid m\u00e5ste vara efter starttid"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.timeline=sv.i18n.portlet.social.timeline||{};
sv.i18n.portlet.social.timeline.timeline=sv.i18n.portlet.social.timeline.timeline||{};sv.i18n.portlet.social.timeline.timeline.de={};
sv.i18n.portlet.social.timeline.timeline.en={loadEntries:"Show more posts",successBookmarkTitle:"Bookmark added",expand:"Expand",comments:"Comments",removeCommentTitle:"Delete comment",removeBookmarkTitle:"Delete bookmark",addComment:"Comment",removeGroupBookmarkTitle:"Delete bookmark from group",commentToLongHeading:"Too long",editCommentTitle:"Edit comment",sharedMessageContentToPersonalTimeline:"The post is now shared on your timeline",editEntryTitle:"Edit post",save:"Save",removeEntryBody:"Are you sure that you want to delete the post?",
hideEntryBody:"Are you sure that you want to hide the post?",showMore:"Show more",collapse:"Collapse",commentToLongBody:"The comment you where trying to post was too long.",sharedPageContentToGroupTimeline:"The page is now shared to group '{0}'",addGroupBookmarkTitle:"Add group bookmark",shareComment:"Add comment",removeCommentBody:"Are you sure you want to delete the comment?",shareEntry:"Share post",tooLargeFileMessage:"The file was to big to upload",sharedPageContentToPersonalTimeline:"The page is now shared to your timeline",
removeEntryTitle:"Delete post",shareMessageContentTitle:"Share in",sharedMessageContentToGroupTimeline:"The post is now shared to group '{0}'",share:"Share",inactiveGroupMessage:"Cannot interact with an inactive group",noMoreEntries:"There are no more posts",showLess:"Show less",successRemovedBookmarkTitle:"Bookmark deleted",hideEntryTitle:"Hide post",sharePageFail:"Failed to share page",sharedMessageTitle:"Shared post",sharedPageTitle:"Shared page",shareMessageContentToPersonalTimeline:"Your own timeline",
successBookmarkMessage:"Bookmark added",addBookmarkTitle:"Add bookmark"};
sv.i18n.portlet.social.timeline.timeline.fi={tooLargeFileMessage:"Tiedosto, jota yritit ladata, oli liian suuri.",expand:"Suurenna",collapse:"Pienenn\u00e4",hideEntryBody:"Oletko varma, ett\u00e4 haluat piilottaa merkinn\u00e4n?",removeEntryBody:"Oletko varma, ett\u00e4 haluat poistaa merkinn\u00e4n?",showLess:"N\u00e4yt\u00e4 v\u00e4hemm\u00e4n",comments:"Kommentteja",shareEntry:"Jaa merkint\u00e4",addComment:"Kommentoi",noMoreEntries:"Ei enemp\u00e4\u00e4 merkint\u00f6j\u00e4",removeCommentBody:"Oletko varma, ett\u00e4 haluat poistaa kommentin?",
removeCommentTitle:"Poista kommentti",sharedMessageContentToPersonalTimeline:"Merkint\u00e4 on jaettu sein\u00e4ll\u00e4si",commentToLongHeading:"Liian pitk\u00e4",removeEntryTitle:"Poista merkint\u00e4",share:"Jaa",sharedMessageTitle:"Jaettu viesti",shareComment:"Jaa kommentti",inactiveGroupMessage:"Sis\u00e4ll\u00f6n muokkaaminen ei ole mahdollista, ryhm\u00e4 ei ole aktiivinen",commentToLongBody:"Kommentti, jota yritit l\u00e4hett\u00e4\u00e4, on liian pitk\u00e4.",showMore:"N\u00e4yt\u00e4 lis\u00e4\u00e4",
hideEntryTitle:"Piilota merkint\u00e4"};
sv.i18n.portlet.social.timeline.timeline.no={loadEntries:"Vis flere innlegg",successBookmarkTitle:"Bokmerke lagt til",expand:"Utvid",comments:"Kommentarer",removeCommentTitle:"Fjern kommentar",removeBookmarkTitle:"Fjern bokmerke",addComment:"Kommenter",removeGroupBookmarkTitle:"Fjern bokmerke fra gruppen",commentToLongHeading:"For lang",editCommentTitle:"Rediger kommentar",sharedMessageContentToPersonalTimeline:"Innlegget er n\u00e5 delt i din flyt",editEntryTitle:"Rediger innlegg",save:"Lagre",removeEntryBody:"Er du sikker p\u00e5 at du vil fjerne innlegget?",
hideEntryBody:"Er du sikker p\u00e5 at du vil skjule innlegget?",showMore:"Vis mer",collapse:"Minimer",commentToLongBody:"Kommentaren du fors\u00f8kte \u00e5 sende, var for lang.",sharedPageContentToGroupTimeline:"Siden er n\u00e5 delt i gruppen '{0}'",addGroupBookmarkTitle:"Legg til gruppebokmerke",shareComment:"Legg til kommentar",removeCommentBody:"Er du sikker p\u00e5 at du vil fjerne kommentaren?",shareEntry:"Del innlegg",tooLargeFileMessage:"Filen du fors\u00f8kte \u00e5 laste opp, var for stor.",
sharedPageContentToPersonalTimeline:"Siden er n\u00e5 delt i din flyt",removeEntryTitle:"Fjern innlegg",shareMessageContentTitle:"Del i",sharedMessageContentToGroupTimeline:"Innlegget er n\u00e5 delt i gruppen '{0}'",share:"Del",inactiveGroupMessage:"Ikke tillatt \u00e5 modifisere innhold i en inaktiv gruppe",noMoreEntries:"Finnes ingen flere innlegg",showLess:"Vis mindre",successRemovedBookmarkTitle:"Bokmerke fjernet",hideEntryTitle:"Skjul innlegg",sharePageFail:"Kunne ikke dele side",sharedMessageTitle:"Delt innlegg",
sharedPageTitle:"Delt side",shareMessageContentToPersonalTimeline:"Din egen flyt",successBookmarkMessage:"Bokmerke lagt til",addBookmarkTitle:"Legg til bokmerke"};
sv.i18n.portlet.social.timeline.timeline.sv={loadEntries:"Visa fler inl\u00e4gg",successBookmarkTitle:"Bokm\u00e4rke tillagt",expand:"Expandera",comments:"Kommentarer",removeCommentTitle:"Ta bort kommentar",removeBookmarkTitle:"Ta bort bokm\u00e4rke",addComment:"Kommentera",removeGroupBookmarkTitle:"Ta bort bokm\u00e4rke fr\u00e5n gruppen",commentToLongHeading:"F\u00f6r l\u00e5ng",editCommentTitle:"Redigera kommentar",sharedMessageContentToPersonalTimeline:"Inl\u00e4gget \u00e4r nu delat i ditt fl\u00f6de",
editEntryTitle:"Redigera inl\u00e4gg",save:"Spara",removeEntryBody:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort inl\u00e4gget?",hideEntryBody:"\u00c4r du s\u00e4ker p\u00e5 att du vill d\u00f6lja inl\u00e4gget?",showMore:"Visa mer",collapse:"Minimera",commentToLongBody:"Kommentaren du f\u00f6rs\u00f6kte skicka var f\u00f6r l\u00e5ng.",sharedPageContentToGroupTimeline:"Sidan \u00e4r nu delad i gruppen '{0}'",addGroupBookmarkTitle:"L\u00e4gg till som bokm\u00e4rke i gruppen",shareComment:"L\u00e4gg till kommentar",
removeCommentBody:"\u00c4r du s\u00e4ker p\u00e5 att du vill ta bort kommentaren?",shareEntry:"Dela inl\u00e4gg",tooLargeFileMessage:"Filen som du f\u00f6rs\u00f6kte ladda upp var f\u00f6r stor.",sharedPageContentToPersonalTimeline:"Sidan \u00e4r nu delad i ditt fl\u00f6de",removeEntryTitle:"Ta bort inl\u00e4gg",shareMessageContentTitle:"Dela i",sharedMessageContentToGroupTimeline:"Inl\u00e4gget \u00e4r nu delat i gruppen '{0}'",share:"Dela",inactiveGroupMessage:"Inte till\u00e5tet att modifiera inneh\u00e5ll i en inaktiv grupp",
noMoreEntries:"Finns inga fler inl\u00e4gg",showLess:"Visa mindre",successRemovedBookmarkTitle:"Bokm\u00e4rke borttaget",hideEntryTitle:"D\u00f6lj inl\u00e4gg",sharePageFail:"Misslyckades att dela sida",sharedMessageTitle:"Delat inl\u00e4gg",sharedPageTitle:"Delad sida",shareMessageContentToPersonalTimeline:"Ditt eget fl\u00f6de",successBookmarkMessage:"Bokm\u00e4rke tillagt",addBookmarkTitle:"L\u00e4gg till som bokm\u00e4rke"};sv.i18n.portlet=sv.i18n.portlet||{};
sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.usercontactsall=sv.i18n.portlet.social.usercontactsall||{};sv.i18n.portlet.social.usercontactsall.usercontactsall=sv.i18n.portlet.social.usercontactsall.usercontactsall||{};sv.i18n.portlet.social.usercontactsall.usercontactsall.de={};sv.i18n.portlet.social.usercontactsall.usercontactsall.en={successMessage:"{0} has been deleted as a contact."};sv.i18n.portlet.social.usercontactsall.usercontactsall.fi={successMessage:"{0} on poistettu kontakteista."};
sv.i18n.portlet.social.usercontactsall.usercontactsall.no={successMessage:"{0} har blitt fjernet som kontakt."};sv.i18n.portlet.social.usercontactsall.usercontactsall.sv={successMessage:"{0} har tagits bort som kontakt."};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.userfields=sv.i18n.portlet.social.userfields||{};sv.i18n.portlet.social.userfields.userfields=sv.i18n.portlet.social.userfields.userfields||{};
sv.i18n.portlet.social.userfields.userfields.de={};
sv.i18n.portlet.social.userfields.userfields.en={errorTitle:"Communication error",dialogTitle:"Profile settings",wrong_password:"Wrong password.",password_field_title:"Password",password_field_description:"To save the values in the directory service, you must enter your password",field_not_writeable:"Field not editable. Contact the administrator.",errorMsg:"Failed to update the information",server_error:"Failed to update the information. An unexpected error occurred.",directory_error:"Failed to update the information. This might happen if you do not have permission if SiteVision failed to connect to the directory server."};
sv.i18n.portlet.social.userfields.userfields.fi={errorTitle:"Yhteysvirhe",dialogTitle:"Profiiliasetukset",wrong_password:"Annoit v\u00e4\u00e4r\u00e4n salasanan.",password_field_title:"Salasana",password_field_description:"Tallentaaksesi tiedot k\u00e4ytt\u00e4j\u00e4hakemistoon, sinun on annettava salasana.",field_not_writeable:"Kentt\u00e4\u00e4n ei voi kirjoittaa. Ota yhteys yll\u00e4pitoon.",errorMsg:"P\u00e4ivitys ep\u00e4onnistui",server_error:"P\u00e4ivitys ep\u00e4onnistui. Tapahtui odottamaton virhe.",
directory_error:"P\u00e4ivitys ep\u00e4onnistui. Oikeutesi eiv\u00e4t ehk\u00e4 riit\u00e4 t\u00e4h\u00e4n toimintoon merkint\u00f6jesi muuttamiseen tai yhteytt\u00e4 k\u00e4ytt\u00e4j\u00e4hakemistoon ei saatu."};
sv.i18n.portlet.social.userfields.userfields.no={errorTitle:"Kommunikasjonsfeil",dialogTitle:"Profilinnstillinger",wrong_password:"Feil passord angitt.",password_field_title:"Passord",password_field_description:"Du m\u00e5 angi passordet ditt for \u00e5 kunne lagre verdiene i katalogtjenesten",field_not_writeable:"Feltet er ikke skrivbart. Kontakt administrator.",errorMsg:"Mislyktes med \u00e5 oppdatere informasjonen",server_error:"Kunne ikke oppdatere informasjonen. Det oppsto en uventet feil.",
directory_error:"Kunne ikke oppdatere informasjonen. Dette kan for eksempel skyldes at du mangler rettigheter til \u00e5 endre p\u00e5 opplysningene eller at du ikke har tilgang til katalogtjenesten."};
sv.i18n.portlet.social.userfields.userfields.sv={errorTitle:"Kommunikationsfel",dialogTitle:"Profilinst\u00e4llningar",wrong_password:"Felaktigt l\u00f6senord angivet.",password_field_title:"L\u00f6senord",password_field_description:"F\u00f6r att kunna spara v\u00e4rdena i katalogtj\u00e4nsten s\u00e5 m\u00e5ste du ange ditt l\u00f6senord",field_not_writeable:"F\u00e4ltet \u00e4r inte skrivbart. Kontakta administrat\u00f6ren.",errorMsg:"Misslyckades med att uppdatera informationen",server_error:"Misslyckades med att uppdatera informationen. Ett ov\u00e4ntat fel uppstod.",
directory_error:"Misslyckades med att uppdatera informationen. Detta kan exempelvis bero p\u00e5 att du saknar r\u00e4ttighet att \u00e4ndra p\u00e5 dina uppgifter eller att det inte g\u00e5r att anropa katalogtj\u00e4nsten."};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.usergroupsall=sv.i18n.portlet.social.usergroupsall||{};sv.i18n.portlet.social.usergroupsall.usergroupsall=sv.i18n.portlet.social.usergroupsall.usergroupsall||{};
sv.i18n.portlet.social.usergroupsall.usergroupsall.de={};
sv.i18n.portlet.social.usergroupsall.usergroupsall.en={leftGroupHeading:"Left group",leftGroupMessage:"You are no longer a member of the group '{0}'.",removeGroupMessage:"You are the last administrator in the group '{0}' and if you leave the group it will be unpublished. Are you sure you want to continue?",removedGroupHeading:"Group removed",removedGroupMessage:"Group '{0}' has been unpublished.",createGroupLabel:"Group name:",createGroupTitle:"Create new group",createdGroupMessage:"Created the group '{0}'.",
createdGroupHeading:"Group created",removeGroupTitle:"Delete group",groupName:"Group name"};
sv.i18n.portlet.social.usergroupsall.usergroupsall.fi={leftGroupHeading:"Piilotettu ryhm\u00e4",leftGroupMessage:"Et ole en\u00e4\u00e4 j\u00e4sen ryhm\u00e4ss\u00e4 '{0}'.",removeGroupMessage:"Olet viimeinen moderaattori ryhm\u00e4ss\u00e4 '{0}' ja jos l\u00e4hdet ryhm\u00e4st\u00e4, se poistetaan. Oletko varma, ett\u00e4 haluat jatkaa?",removedGroupHeading:"Ryhm\u00e4 poistettu",removedGroupMessage:"Ryhm\u00e4 '{0}' on piilotettu.",createGroupLabel:"Ryhm\u00e4n nimi:",createGroupTitle:"Luo uusi ryhm\u00e4",
createdGroupMessage:"Ryhm\u00e4 '{0}' on nyt luotu.",createdGroupHeading:"Luo ryhm\u00e4",removeGroupTitle:"Poista ryhm\u00e4",groupName:"Ryhm\u00e4n nimi"};
sv.i18n.portlet.social.usergroupsall.usergroupsall.no={leftGroupHeading:"Forlot gruppe",leftGroupMessage:"Du er ikke lenger medlem av gruppen '{0}'.",removeGroupMessage:"Du er den siste administratoren i gruppen '{0}', og hvis du forlater gruppen, vil den bli avpublisert. Er du sikker p\u00e5 at du vil fortsette?",removedGroupHeading:"Gruppe fjernet",removedGroupMessage:"Gruppen '{0}' er avpublisert.",createGroupLabel:"Gruppenavn:",createGroupTitle:"Opprett ny gruppe",createdGroupMessage:'Opprettet gruppen "{0}".',
createdGroupHeading:"Gruppe opprettet",removeGroupTitle:"Fjern gruppe",groupName:"Gruppenavn"};
sv.i18n.portlet.social.usergroupsall.usergroupsall.sv={leftGroupHeading:"L\u00e4mnade grupp",leftGroupMessage:"Du \u00e4r inte l\u00e4ngre medlem i gruppen '{0}'.",removeGroupMessage:"Du \u00e4r den sista administrat\u00f6ren i gruppen '{0}' och om du l\u00e4mnar gruppen s\u00e5 kommer den att avpubliceras. \u00c4r du s\u00e4ker p\u00e5 att du vill forts\u00e4tta?",removedGroupHeading:"Grupp borttagen",removedGroupMessage:"Gruppen '{0}' har avpublicerats.",createGroupLabel:"Gruppnamn:",createGroupTitle:"Skapa ny grupp",
createdGroupMessage:"Skapade gruppen '{0}'.",createdGroupHeading:"Grupp skapad",removeGroupTitle:"Ta bort grupp",groupName:"Gruppnamn"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.util=sv.i18n.portlet.util||{};sv.i18n.portlet.util.userinformation=sv.i18n.portlet.util.userinformation||{};sv.i18n.portlet.util.userinformation.de={};sv.i18n.portlet.util.userinformation.en={message:"Message",addAsContact:"Add as contact"};sv.i18n.portlet.util.userinformation.fi={};
sv.i18n.portlet.util.userinformation.no={message:"Melding",addAsContact:"Legg til som kontakt"};sv.i18n.portlet.util.userinformation.sv={message:"Meddelande",addAsContact:"L\u00e4gg till som kontakt"};sv.i18n.portlet=sv.i18n.portlet||{};sv.i18n.portlet.social=sv.i18n.portlet.social||{};sv.i18n.portlet.social.videocall=sv.i18n.portlet.social.videocall||{};sv.i18n.portlet.social.videocall.videocall=sv.i18n.portlet.social.videocall.videocall||{};
sv.i18n.portlet.social.videocall.videocall.en={callMessage:"Video call from {0}, answer?",roomName:"Conference name:"};sv.i18n.portlet.social.videocall.videocall.no={callMessage:"Videosamtale fra {0}, svare?",roomName:"Konferansenavn:"};sv.i18n.portlet.social.videocall.videocall.sv={callMessage:"Videosamtal fr\u00e5n {0}, svara?",roomName:"Konferensnamn:"};sv.i18n.util=sv.i18n.util||{};sv.i18n.util.viewutil=sv.i18n.util.viewutil||{};sv.i18n.util.viewutil.de={};sv.i18n.util.viewutil.en={selectView:"Select view"};
sv.i18n.util.viewutil.fi={selectView:"Valitse n\u00e4kym\u00e4"};sv.i18n.util.viewutil.no={selectView:"Velg visning"};sv.i18n.util.viewutil.sv={selectView:"V\u00e4lj vy"};
