# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2020-12-02 14:38

from django.db import migrations


def seed_profiles(apps, schema_editor):
    # We can't import the Profile model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Profile = apps.get_model('users', 'Profile')
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        p = Profile(user=user)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_profiles)
    ]
