# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_guildeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='guildeline',
            new_name='guideline',
        ),
    ]
