# Generated by Django 2.2.2 on 2019-06-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition')], max_length=10),
        ),
        migrations.AlterField(
            model_name='marker',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition')], max_length=10),
        ),
    ]
