# Generated by Django 2.2.2 on 2019-06-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190619_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('impossible', models.BooleanField(default=False)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Context')),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='datapoint',
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.AddField(
            model_name='label',
            name='input',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Input'),
            preserve_default=False,
        ),
    ]
