# Generated by Django 2.2.2 on 2019-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190619_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='label_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
