# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190624_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
