# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190624_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_published_project', 'View published project')]},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profiles', to='projects.Project'),
        ),
    ]
