# Generated by Django 2.2.2 on 2019-06-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_context_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Context'),
        ),
        migrations.AlterField(
            model_name='project',
            name='context_size',
            field=models.CharField(choices=[('no', 'No context'), ('t', 'Text'), ('p', 'Paragraph')], max_length=2),
        ),
    ]
