# Generated by Django 2.2.2 on 2019-07-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190628_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
