# Generated by Django 2.2.2 on 2019-08-27 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0023_auto_20190823_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='is_match',
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_review',
        ),
        migrations.CreateModel(
            name='LabelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(null=True)),
                ('ambiguity_status', models.CharField(choices=[('no', 'No ambiguity'), ('rr', 'Requires resolution'), ('rs', 'Resolved')], default='no', max_length=2)),
                ('start', models.PositiveIntegerField(null=True)),
                ('end', models.PositiveIntegerField(null=True)),
                ('impossible', models.BooleanField(default=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Marker')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Label')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
