# Generated by Django 2.2.2 on 2019-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20190827_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='shortcut',
            field=models.CharField(help_text='Keyboard shortcut for marking a piece of text with this label', max_length=10, null=True),
        ),
    ]
