# Generated by Django 2.2.2 on 2019-08-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190828_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Context'),
        ),
        migrations.AlterField(
            model_name='label',
            name='input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Input'),
        ),
    ]
