# Generated by Django 2.2.2 on 2019-08-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20190829_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='asking_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timed_questions',
            field=models.IntegerField(default=0),
        ),
    ]
