# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20190829_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='labelreview',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_created',
            field=models.DateTimeField(null=True),
        ),
    ]
