# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20190829_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
