# Generated by Django 2.2.2 on 2019-09-05 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20190904_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='label_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='type',
        ),
        migrations.AlterField(
            model_name='marker',
            name='short',
            field=models.CharField(default='d', help_text='By default the capitalized first three character of the label', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('for_task_type', models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution')], max_length=10)),
                ('direction', models.CharField(choices=[('fs', 'Directed from the first to the second'), ('sf', 'Directed from the second to the first'), ('bd', 'Bi-directional')], max_length=2)),
                ('first_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_node', to='projects.Marker')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('second_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_node', to='projects.Marker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('first_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_label', to='projects.Label')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Relation')),
                ('second_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_label', to='projects.Label')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
