# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-20 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20190905_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcessingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=50)),
                ('helper', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='post_processing_methods',
            field=models.ManyToManyField(to='projects.PostProcessingMethod'),
        ),
    ]
