# Generated by Django 2.2.2 on 2019-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20190920_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postprocessingmethod',
            options={'verbose_name': 'Post-processing method', 'verbose_name_plural': 'Post-processing methods'},
        ),
        migrations.AddField(
            model_name='project',
            name='max_markers',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('TextFile', 'Plain text file(s)'), ('Db', 'Database'), ('Json', 'JSON file(s)')], max_length=10),
        ),
    ]
