# Generated by Django 2.2.2 on 2019-09-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20190921_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='max_markers',
            new_name='max_markers_per_input',
        ),
    ]
