# Generated by Django 2.2.2 on 2019-09-21 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20190921_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='undone',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PreMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tokens', models.TextField(help_text='Comma-separated tokens that should be highlighted with a marker')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Marker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
