# Generated by Django 2.2.2 on 2019-09-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20190921_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premarker',
            options={'verbose_name': 'Pre-marker', 'verbose_name_plural': 'Pre-markers'},
        ),
    ]
