# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_auto_20190921_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_markers_per_input',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
