# Generated by Django 2.2.2 on 2019-09-23 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20190921_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='guideline',
            new_name='guidelines',
        ),
        migrations.AlterField(
            model_name='context',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='input',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='label',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='labelrelation',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='labelreview',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='level',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='postprocessingmethod',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='premarker',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_finish',
            field=models.DateTimeField(verbose_name='To be finished at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_publish',
            field=models.DateTimeField(verbose_name='To be published at'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
    ]
