# Generated by Django 2.2.2 on 2019-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20190924_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelrelation',
            name='undone',
            field=models.BooleanField(default=False),
        ),
    ]
