# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_labelrelation_undone'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='batch',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='labelrelation',
            name='batch',
            field=models.UUIDField(null=True),
        ),
    ]
