# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20190927_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
