# Generated by Django 2.2.2 on 2019-10-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20191011_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='points_scope',
            field=models.CharField(choices=[('n', 'No points'), ('i', 'Per input'), ('l', 'Per label')], default='n', help_text='The scope of the submitted task', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='points_unit',
            field=models.PositiveIntegerField(default=1, help_text='Number of points per submitted task'),
        ),
    ]
