# Generated by Django 2.2.2 on 2019-10-16 09:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20191016_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guidelines',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
