# Generated by Django 2.2.2 on 2019-10-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20191018_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.DataSource'),
        ),
    ]
