# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-10-24 10:20

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_context_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_guideline',
            field=filebrowser.fields.FileBrowseField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('PlainText', 'Plain text'), ('TextFile', 'Plain text file(s)'), ('Db', 'Database'), ('Json', 'JSON file(s)')], max_length=10),
        ),
    ]
