# Generated by Django 2.2.2 on 2019-10-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20191024_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='video_guideline',
            new_name='video_guidelines',
        ),
    ]
