# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-10-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20191024_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='video_guidelines',
            new_name='video_summary',
        ),
    ]
