# Generated by Django 2.2.2 on 2019-10-24 12:46

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_auto_20191024_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='supported_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_summary',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=1000, null=True),
        ),
    ]
