# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-10-25 09:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20191024_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guidelines',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
