# Generated by Django 2.2.2 on 2019-10-28 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_project_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='project',
        ),
        migrations.CreateModel(
            name='MarkerCountRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('restriction_type', models.CharField(choices=[('no', '-'), ('ls', '<'), ('le', '<='), ('gs', '>'), ('ge', '>=')], default='no', max_length=2)),
                ('restriction_value', models.PositiveIntegerField(default=0)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Marker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='markers',
            field=models.ManyToManyField(blank=True, through='projects.MarkerCountRestriction', to='projects.Marker'),
        ),
    ]
