# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-11-12 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0063_auto_20191029_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DataSource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sampling_with_replacement',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='datasources',
        ),
        migrations.AddField(
            model_name='project',
            name='datasources',
            field=models.ManyToManyField(through='projects.ProjectData', to='projects.DataSource'),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_datapoint', models.PositiveIntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('project_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
