# Generated by Django 2.2.2 on 2019-11-12 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0064_auto_20191112_1255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataaccesslog',
            unique_together={('user', 'project_data')},
        ),
        migrations.AlterUniqueTogether(
            name='markercountrestriction',
            unique_together={('project', 'marker', 'restriction_type')},
        ),
        migrations.AlterUniqueTogether(
            name='projectdata',
            unique_together={('project', 'datasource')},
        ),
    ]
