# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20191112_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='accessed_datapoints',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
