# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-11-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20191113_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='accessed_datapoints',
        ),
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='last_datapoint',
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='datapoint',
            field=models.CharField(default='0', max_length=64),
            preserve_default=False,
        ),
    ]
