# Generated by Django 2.2.2 on 2019-11-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20191113_0859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataaccesslog',
            unique_together=set(),
        ),
    ]
