# Generated by Django 2.2.2 on 2019-11-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20191113_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
