# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2020-12-02 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20200612_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='input',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='label',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='labelrelation',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='labelreview',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='level',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='markercountrestriction',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='postprocessingmethod',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='premarker',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date'),
        ),
    ]
