# Generated by Django 2.2.2 on 2020-12-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20201202_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disable_submitted_labels',
            field=models.BooleanField(default=True),
        ),
    ]
