# Generated by Django 2.2.2 on 2021-01-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_auto_20210105_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allow_commenting_on_labels',
        ),
    ]
