# Generated by Django 2.2.2 on 2021-01-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_auto_20210108_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='markercontextmenuitem',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
