# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20210111_1925'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['project'], name='projects_la_project_777638_idx'),
        ),
        migrations.AddIndex(
            model_name='labelrelation',
            index=models.Index(fields=['project'], name='projects_la_project_8c0957_idx'),
        ),
    ]
