# Generated by Django 3.1.5 on 2021-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_auto_20210116_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='markercontextmenuitem',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
