# Generated by Django 3.1.5 on 2021-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_markercontextmenuitem_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='representation',
            field=models.CharField(choices=[('g', 'Graph'), ('l', 'list')], default='g', help_text='How the relation should be visualized?', max_length=1),
        ),
    ]
