# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_relation_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='markercontextmenuitem',
            name='admin_filter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='representation',
            field=models.CharField(choices=[('g', 'Graph'), ('l', 'List')], default='g', help_text='How the relation should be visualized?', max_length=1),
        ),
    ]
