# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-01-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20210125_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='markercontextmenuitem',
            name='verbose_admin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
