# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_markercontextmenuitem_verbose_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
