# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_auto_20210211_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_dataset_identifiers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marker',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='context_size',
            field=models.CharField(choices=[('no', 'No context'), ('t', 'Text'), ('p', 'Paragraph')], help_text='Context size for storing labels', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relation',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic')], max_length=10),
        ),
    ]
