# Generated by Django 3.1.5 on 2021-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_auto_20210315_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disjoint_annotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=models.CharField(choices=[('danger', 'Red'), ('success', 'Green'), ('warning', 'Yellow'), ('link', 'Dark Blue'), ('info', 'Light Blue'), ('primary', 'Teal'), ('black', 'Black'), ('grey', 'Grey'), ('warndark', 'Dark Yellow'), ('pink', 'Pink'), ('orange', 'Orange')], max_length=10),
        ),
    ]
