# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-04-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_auto_20210430_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sampling_with_replacement',
            field=models.BooleanField(default=False),
        ),
    ]
