# Generated by Django 3.1.5 on 2021-06-22 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_auto_20210430_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('mcq', 'Multiple Choice Question Answering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('mcq', 'Multiple Choice Question Answering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relation',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('mcq', 'Multiple Choice Question Answering')], max_length=10),
        ),
        migrations.RenameModel('MarkerCountRestriction', 'MarkerVariant'),
        migrations.AddField(
            model_name='markervariant',
            name='is_free_text',
            field=models.BooleanField(default=False)
        )
    ]
