# Generated by Django 3.1.5 on 2021-06-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20210623_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='markervariant',
            name='order_in_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
