# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0095_auto_20210625_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='batch',
            field=models.UUIDField(default="00000000-0000-0000-0000-000000000000"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.marker'),
        ),
        migrations.AddField(
            model_name='input',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='input',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='input',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='label',
            name='impossible',
        ),
    ]
