# Generated by Django 3.1.5 on 2021-06-26 10:55

from django.db import migrations, models


def set_missing_fields_for_inputs(apps, schema_editor):
    Input = apps.get_model('projects', 'Input')
    Label = apps.get_model('projects', 'Label')
    for inp in Input.objects.all().iterator():
        label = Label.objects.filter(input=inp).first()
        if not label: continue
        if label.batch:
            inp.batch = label.batch
        inp.project = label.project
        inp.user = label.user
        inp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_auto_20210626_1030'),
    ]

    operations = [
        migrations.RunPython(set_missing_fields_for_inputs),
    ]
