# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_auto_20210626_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='project',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='label',
            name='batch',
            field=models.UUIDField(default="00000000-0000-0000-0000-000000000000"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='label',
            name='input',
        ),
    ]
