# Generated by Django 3.1.5 on 2021-06-26 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_auto_20210626_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date')),
                ('uuid', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='input',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.markervariant'),
        ),
        migrations.AddField(
            model_name='label',
            name='marker_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.markervariant'),
        ),
    ]
