# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_auto_20210626_1253'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='label',
            name='projects_la_project_777638_idx',
        ),
        migrations.RemoveField(
            model_name='input',
            name='project',
        ),
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.RemoveField(
            model_name='label',
            name='marker',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='marker_variant',
            new_name='marker',
        ),
        migrations.AddField(
            model_name='input',
            name='batch2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.batch'),
        ),
        migrations.AddField(
            model_name='label',
            name='batch2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.batch'),
        ),
        migrations.AddField(
            model_name='labelrelation',
            name='batch2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.batch'),
        ),
    ]
