# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 13:01

from django.db import migrations


def create_batches(apps, schema_editor):
    Batch = apps.get_model('projects', 'Batch')
    Input = apps.get_model('projects', 'Input')
    Label = apps.get_model('projects', 'Label')
    LabelRelation = apps.get_model('projects', 'LabelRelation')
    for inp in Input.objects.all().iterator():
        b, _ = Batch.objects.get_or_create(uuid=inp.batch)
        inp.batch2 = b
        inp.save()

    for l in Label.objects.all().iterator():
        b, _ = Batch.objects.get_or_create(uuid=l.batch)
        l.batch2 = b
        l.save()

    for l in LabelRelation.objects.all().iterator():
        b, _ = Batch.objects.get_or_create(uuid=l.batch)
        l.batch2 = b
        l.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_auto_20210626_1301'),
    ]

    operations = [
        migrations.RunPython(create_batches, migrations.RunPython.noop),
    ]
