# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0103_auto_20210626_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='input',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='labelrelation',
            name='batch',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='batch2',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='batch2',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='labelrelation',
            old_name='batch2',
            new_name='batch',
        ),
    ]
