# Generated by Django 3.1.5 on 2021-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0104_auto_20210626_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveIndex(
            model_name='labelrelation',
            name='projects_la_project_8c0957_idx',
        ),
        migrations.RemoveField(
            model_name='labelrelation',
            name='project',
        ),
        migrations.AddField(
            model_name='labelrelation',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
