# Generated by Django 3.1.5 on 2021-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_auto_20210626_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerunit',
            name='minimum_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='markerunit',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='markervariant',
            name='order_in_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
