# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_project_has_intro_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='is_submitted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
