# Generated by Django 3.1.5 on 2021-12-01 12:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_auto_20211201_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text="Marker's color used when annotating the text", max_length=18),
        ),
    ]
