# Generated by Django 3.2.10 on 2021-12-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0117_fix_context_menu_items_20211223_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markercontextmenuitem',
            name='marker',
        ),
        migrations.AlterField(
            model_name='markercontextmenuitem',
            name='markerv',
            field=models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='projects.markervariant', verbose_name='marker'),
        ),
        migrations.RenameField(
            model_name='markercontextmenuitem',
            old_name='markerv',
            new_name='marker',
        ),
    ]
