# Generated by Django 3.2.10 on 2021-12-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0122_auto_20211227_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='context_size',
        ),
        migrations.AlterField(
            model_name='project',
            name='datasources',
            field=models.ManyToManyField(help_text='All datasets must of the same language as the project', through='projects.ProjectData', to='projects.DataSource', verbose_name='data sources'),
        ),
    ]
