# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2021-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0123_auto_20211228_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='datapoint',
            field=models.CharField(blank=True, help_text='As stored in the original dataset', max_length=64, null=True, verbose_name='datapoint ID'),
        ),
    ]
