# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-01-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0124_context_datapoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-dt_finish'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='batch',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='context',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='formatting',
            field=models.CharField(choices=[('md', 'Markdown'), ('ft', 'Formatted text'), ('pt', 'Plain text')], default='md', help_text='text formating of the data source', max_length=3, verbose_name='formatting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='label',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='labelrelation',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='labelreview',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='level',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='marker',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='markeraction',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='markercontextmenuitem',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='markerpair',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='markerrestriction',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='markerunit',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='markervariant',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='postprocessingmethod',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='premarker',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='A thumbnail of your project (ignored if not provided)', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_remote',
            field=models.URLField(blank=True, help_text='A URL for video summary to be embedded (e.g. from YouTube)', null=True),
        ),
        migrations.AddField(
            model_name='projectdata',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='relation',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dt_updated',
            field=models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at'),
        ),
    ]
