# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-01-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0126_auto_20220105_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.context'),
        ),
        migrations.RemoveField(
            model_name='markervariant',
            name='is_free_text',
        ),
        migrations.AlterField(
            model_name='premarker',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.markervariant'),
        ),
    ]
