# Generated by Django 3.2.10 on 2022-01-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0128_auto_20220109_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markerunit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='project',
        )
    ]
