# Generated by Django 3.2.10 on 2022-01-11 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0129_auto_20220109_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypeSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Autofilled', null=True, verbose_name='Created at')),
                ('dt_updated', models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at')),
                ('task_type', models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('ranking', 'Ranking')], max_length=10, verbose_name='type of the annotation task')),
                ('config', models.JSONField(verbose_name='JSON configuration')),
            ],
            options={
                'verbose_name': 'task type specification',
                'verbose_name_plural': 'task type specification',
            },
        ),
        migrations.AlterField(
            model_name='markervariant',
            name='nrange',
            field=models.ForeignKey(blank=True, help_text="\n            Applicable only if the annotation types are 'integer', 'floating-point number' or 'range'.\n            If the annotation type is 'range' and no numeric range is specified, the input will range from 0 to 100 by default.\n            The values will remain unrestricted for 'integer' or 'floating-point number' types.\n            ", null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.range', verbose_name='numeric range'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('ranking', 'Ranking')], max_length=10, verbose_name='type of the annotation task'),
        ),
    ]
