# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-01-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0130_auto_20220111_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'permissions': (('view_this_datasource', 'View this data source'), ('change_this_datasource', 'Change this data source'), ('delete_this_datasource', 'Delete this data source')), 'verbose_name': 'data source', 'verbose_name_plural': 'data sources'},
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={'permissions': (('change_this_marker', 'Change this marker'), ('delete_this_marker', 'Delete this marker')), 'verbose_name': 'marker', 'verbose_name_plural': 'markers'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-dt_finish'], 'permissions': (('view_this_project', 'Can view this project'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'permissions': (('change_this_relation', 'Change this relation'), ('delete_this_relation', 'Delete this relation')), 'verbose_name': 'relation', 'verbose_name_plural': 'relations'},
        ),
        migrations.AddField(
            model_name='datasource',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether to make data source available to other Textinator users', verbose_name='is public?'),
        ),
        migrations.AddField(
            model_name='marker',
            name='name_ru',
            field=models.CharField(help_text='The display name of the marker (max 50 characters)', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='relation',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], help_text='Language of this data source', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], help_text='Language of this project', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('mcqa', 'Multiple Choice Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('pronr', 'Pronoun Resolution'), ('ranking', 'Ranking'), ('tclass', 'Text Classification'), ('mt', 'Machine Translation')], max_length=10, verbose_name='type of the annotation task'),
        ),
        migrations.AlterField(
            model_name='tasktypespecification',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('mcqa', 'Multiple Choice Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('pronr', 'Pronoun Resolution'), ('ranking', 'Ranking'), ('tclass', 'Text Classification'), ('mt', 'Machine Translation')], max_length=10, verbose_name='type of the annotation task'),
        ),
    ]
