# Generated by Django 3.2.10 on 2022-01-13 17:32

from django.db import migrations, models
import django.db.models.deletion


def fix_access_logs(apps, schema_editor):
    ProjectData = apps.get_model('projects', 'ProjectData')
    DataAccessLog = apps.get_model('projects', 'DataAccessLog')
    
    for da in DataAccessLog.objects.all():
        da.project = da.project_data.project
        da.datasource = da.project_data.datasource
        da.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0131_auto_20220113_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'a project-specific user profile', 'verbose_name_plural': 'project specific user profiles'},
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.datasource'),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.RunPython(fix_access_logs, migrations.RunPython.noop),
    ]
