# Generated by Django 3.2.10 on 2022-01-13 17:46

from django.db import migrations, models
import django.db.models.deletion


def fix_project_datasources(apps, schema_editor):
    DataAccessLog = apps.get_model('projects', 'DataAccessLog')
    Project = apps.get_model('projects', 'Project')
    
    for p in Project.objects.all():
        da_datasources = set(DataAccessLog.objects.filter(project=p).values_list('datasource', flat=True).all())

        for ds in da_datasources:
            p.datasources.add(ds)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0132_auto_20220113_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='project_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='datasources',
        ),
        migrations.AddField(
            model_name='project',
            name='datasources',
            field=models.ManyToManyField(help_text='All data sources must be of the same language as the project', to='projects.DataSource', verbose_name='data sources'),
        ),
        migrations.RunPython(fix_project_datasources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='datasource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.datasource'),
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.DeleteModel(
            name='ProjectData',
        ),
    ]
