# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-01-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0135_auto_20220115_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('mcqa', 'Multiple Choice Question Answering'), ('mcqar', 'Multiple Choice Question Answering with Ranking'), ('ner', 'Named Entity Recognition'), ('pronr', 'Pronoun Resolution'), ('corr', 'Coreference Resolution'), ('mt', 'Machine Translation')], max_length=10, verbose_name='type of the annotation task'),
        ),
        migrations.AlterField(
            model_name='relationvariant',
            name='custom_representation',
            field=models.CharField(blank=True, choices=[('g', 'Graph'), ('l', 'List')], default='g', help_text='How should the relation be visualized? (representation of the relation template by default)', max_length=1, null=True, verbose_name='graphical representation type'),
        ),
        migrations.AlterField(
            model_name='tasktypespecification',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('mcqa', 'Multiple Choice Question Answering'), ('mcqar', 'Multiple Choice Question Answering with Ranking'), ('ner', 'Named Entity Recognition'), ('pronr', 'Pronoun Resolution'), ('corr', 'Coreference Resolution'), ('mt', 'Machine Translation')], max_length=10, verbose_name='type of the annotation task'),
        ),
    ]
