# Generated by Django 3.2.10 on 2022-02-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0137_alter_labelrelation_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='points_scope',
        ),
        migrations.RemoveField(
            model_name='project',
            name='points_unit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='round_length',
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='flags',
            field=models.TextField(blank=True, default='', help_text='Additional information provided by the annotator', verbose_name='flags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='should the project be public?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('qar', 'Question Answering with Ranking'), ('mcqa', 'Multiple Choice Question Answering'), ('mcqar', 'Multiple Choice Question Answering with Ranking'), ('ner', 'Named Entity Recognition'), ('pronr', 'Pronoun Resolution'), ('corr', 'Coreference Resolution'), ('mt', 'Machine Translation')], max_length=10, verbose_name='type of the annotation task'),
        ),
        migrations.AlterField(
            model_name='tasktypespecification',
            name='task_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('qa', 'Question Answering'), ('qar', 'Question Answering with Ranking'), ('mcqa', 'Multiple Choice Question Answering'), ('mcqar', 'Multiple Choice Question Answering with Ranking'), ('ner', 'Named Entity Recognition'), ('pronr', 'Pronoun Resolution'), ('corr', 'Coreference Resolution'), ('mt', 'Machine Translation')], max_length=10, verbose_name='type of the annotation task'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
