# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0138_auto_20220218_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='asking_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timed_questions',
        ),
        migrations.AlterField(
            model_name='markervariant',
            name='custom_suggestion_endpoint',
            field=models.URLField(blank=True, help_text='\n            Custom endpoint for the Suggestions API (by default the one from the marker template is used).\n            Activates only if suggestions are enabled.\n            ', null=True),
        ),
    ]
