# Generated by Django 3.2.13 on 2022-06-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0141_labelrelation_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='name_es',
            field=models.CharField(help_text='The display name of the marker (max 50 characters)', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='marker',
            name='name_nl',
            field=models.CharField(help_text='The display name of the marker (max 50 characters)', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='relation',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='relation',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], help_text='Language of this data source', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], help_text='Language of this project', max_length=10, verbose_name='language'),
        ),
    ]
