# Generated by Django 3.2.10 on 2022-04-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0141_labelrelation_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelrelation',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.relationvariant'),
        ),
    ]
