# Generated by Django 3.2.15 on 2022-08-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0144_auto_20220819_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sampling_with_replacement',
        ),
        migrations.AddField(
            model_name='project',
            name='data_order',
            field=models.CharField(choices=[('os', 'Specified order (sequential datasets)'), ('op', 'Specified order (parallel datasets)'), ('r', 'Random order (without replacement)'), ('rr', 'Random order (with replacement)')], default='r', max_length=2, verbose_name='in what order should the data be presented?'),
        ),
    ]
