# Generated by Django 3.2.15 on 2022-08-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0145_auto_20220824_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccesslog',
            name='datapoint',
            field=models.IntegerField(help_text='As ordered in the original dataset', verbose_name='datapoint ID'),
        ),
    ]
