# Generated by Django 3.2.15 on 2022-10-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0147_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='markervariant',
            name='choices',
            field=models.JSONField(blank=True, help_text='Valid only if annotation type is `radio buttons` or `checkboxes`', null=True, verbose_name='Choices for the values this marker'),
        ),
        migrations.AlterField(
            model_name='markervariant',
            name='anno_type',
            field=models.CharField(choices=[('m-span', 'Marker (text spans)'), ('m-text', 'Marker (whole text)'), ('free-text', 'Short free-text input'), ('lfree-text', 'Long free-text input'), ('integer', 'Integer'), ('float', 'Floating-point number'), ('range', 'Range'), ('radio', 'Radio buttons'), ('check', 'Checkboxes')], default='m-span', help_text='The type of annotations made using this marker', max_length=10, verbose_name='annotation type'),
        ),
    ]
