# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0149_auto_20221019_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modal_configs',
            field=models.JSONField(blank=True, help_text="JSON configuration for the modal windows in the project. Currently available keys for modals are: 'flagged'", null=True, verbose_name="Configuration for the fields included in project's modal windows"),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('PlainText', 'Plain text'), ('TextFile', 'Plain text file(s)'), ('Json', 'JSON file(s)'), ('TextsAPI', 'Texts API')], max_length=10, verbose_name='dataset type'),
        ),
    ]
