# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-02 08:12

import json
from django.db import migrations, models
import projects.models


def reassign_flags(apps, schema_editor):
    DataAccessLog = apps.get_model('projects', 'DataAccessLog')

    flagged = DataAccessLog.objects.exclude(flags="")
    altered = 0

    for f_dal in flagged:
        try:
            json.loads(f_dal.flags)
        except json.decoder.JSONDecodeError:
            f_dal.flags_j = {
                "text_errors": f_dal.flags
            }
            f_dal.save()
            altered += 1

    if altered > 0:
        print("Altered {} access logs".format(altered))


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0150_auto_20221102_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='flags_j',
            field=models.JSONField(blank=True, default=projects.models.get_default_flags_dict, help_text='Additional information provided by the annotator', null=True, verbose_name='flags'),
        ),
        migrations.RunPython(reassign_flags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='flags'
        ),
        migrations.RenameField(
            model_name='dataaccesslog',
            old_name='flags_j',
            new_name='flags'
        )
    ]
