# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0151_alter_dataaccesslog_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='is_delayed',
            field=models.BooleanField(default=False, help_text='Indicates whether the datapoint for skipped and saved for later by an annotator', verbose_name='is saved for later?'),
        ),
    ]
