# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0152_dataaccesslog_is_delayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerrestriction',
            name='is_ignorable',
            field=models.BooleanField(default=False, help_text='whether the restriction can be ignored at the discretion of the annotator', verbose_name='can be ignored?'),
        ),
    ]
