# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0154_project_editing_title_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Indicates whether the annotator has flagged the batch as having problems', verbose_name='flagged?'),
        ),
    ]
