# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0158_auto_20221107_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editing_as_revision',
            field=models.BooleanField(default=False, help_text='\n        By default editing happens directly in the annotated objects. If this setting is turned on,\n        the original objects will remain intact and separate reivison objects will be created', verbose_name='should editing be saved as revisions?'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.batch'),
        ),
        migrations.AlterField(
            model_name='input',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.input'),
        ),
        migrations.AlterField(
            model_name='label',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.label'),
        ),
    ]
