# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-12-17 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0160_auto_20221213_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Autofilled', null=True, verbose_name='Created at')),
                ('dt_updated', models.DateTimeField(help_text='Autofilled', null=True, verbose_name='Updated at')),
                ('task', models.TextField(help_text='name of a Celery task', verbose_name='task')),
                ('token', models.CharField(blank=True, help_text='Celery task ID', max_length=36, null=True, verbose_name='token')),
                ('finished', models.BooleanField(default=False, verbose_name='is finished?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
