repos:
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types: [css, javascript]
        log_file: pre-commit.log
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
        log_file: pre-commit.log
    -   id: end-of-file-fixer
        log_file: pre-commit.log
    -   id: check-yaml
        log_file: pre-commit.log
    -   id: check-json
        log_file: pre-commit.log
    -   id: check-added-large-files
        log_file: pre-commit.log
    -   id: check-symlinks
        log_file: pre-commit.log
    -   id: fix-encoding-pragma
        log_file: pre-commit.log
    -   id: requirements-txt-fixer
        log_file: pre-commit.log
