version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.4-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${TT_DB_USER}
      - POSTGRES_PASSWORD=${TT_DB_PASSWORD}
      - POSTGRES_DB=${TT_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TT_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: