version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=textinator
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=textinator

volumes:
  postgres_data: