# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190619_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('TextFile', 'Plain text file(s)'), ('Elastic', 'ElasticSearch index'), ('Db', 'Database'), ('Json', 'JSON file(s)')], max_length=10)),
                ('spec', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('qa', 'Question Answering')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='datasources',
            field=models.ManyToManyField(to='projects.DataSource'),
        ),
    ]
