# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190619_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='short',
            field=models.CharField(blank=True, help_text='By default the capitalized first three character of the label', max_length=10, null=True),
        ),
    ]
