# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190624_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='content_hash',
        ),
    ]
