# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_context_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context_size',
            field=models.CharField(choices=[('t', 'Text'), ('p', 'Paragraph'), ('s', 'Sentence')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
