# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-08-23 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_project_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='impossible',
        ),
        migrations.AddField(
            model_name='input',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='impossible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='label',
            name='is_match',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_peer_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
