# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20190920_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='post_processing_methods',
            field=models.ManyToManyField(blank=True, to='projects.PostProcessingMethod'),
        ),
    ]
