# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-24 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0043_auto_20190923_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='project',
        ),
        migrations.RemoveField(
            model_name='input',
            name='user',
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labelrelation',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labelrelation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
