# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20190924_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='round_length',
            field=models.PositiveIntegerField(blank=True, help_text='The number of text snippets consituting one round of the game', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_markers_per_input',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
