# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-10-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20191028_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markercountrestriction',
            name='restriction_type',
            field=models.CharField(choices=[('no', '-'), ('ls', '<'), ('le', '<='), ('gs', '>'), ('ge', '>='), ('eq', '=')], default='no', max_length=2),
        ),
    ]
