# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2019-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_label_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_commenting_on_labels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_selecting_labels',
            field=models.BooleanField(default=False),
        ),
    ]
