# -*- coding: utf-8 -*-
# Generated by Django 2.2.2 on 2021-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_markercontextmenuitem_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Keyboard shortcut for marking a piece of text with this label', max_length=15, null=True),
        ),
    ]
