# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-01-16 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_auto_20210115_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='first_node',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='second_node',
        ),
        migrations.CreateModel(
            name='MarkerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='projects.marker')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='projects.marker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='pairs',
            field=models.ManyToManyField(to='projects.MarkerPair'),
        ),
    ]
