# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-23 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_auto_20210622_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date')),
                ('size', models.IntegerField(default=1)),
                ('is_rankable', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Internal name for the unit (max 10 characters)', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='marker',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('ranking', 'Ranking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('ranking', 'Ranking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relation',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('ranking', 'Ranking')], max_length=10),
        ),
        migrations.AddField(
            model_name='markervariant',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.markerunit'),
        ),
        migrations.AlterUniqueTogether(
            name='markervariant',
            unique_together={('project', 'marker', 'restriction_type', 'unit')},
        ),
    ]
