# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-25 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_markervariant_order_in_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markervariant',
            unique_together={('project', 'marker', 'unit')},
        ),
        migrations.CreateModel(
            name='MarkerRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='creation date')),
                ('kind', models.CharField(choices=[('no', '-'), ('ls', '<'), ('le', '<='), ('gs', '>'), ('ge', '>='), ('eq', '=')], max_length=2)),
                ('value', models.PositiveIntegerField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.markervariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='markervariant',
            name='restriction_type',
        ),
        migrations.RemoveField(
            model_name='markervariant',
            name='restriction_value',
        ),
    ]
