# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 10:55

from django.db import migrations


def delete_inputs_without_project(apps, schema_editor):
    Input = apps.get_model('projects', 'Input')
    Input.objects.filter(project__pk=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_auto_20210626_1055'),
    ]

    operations = [
        migrations.RunPython(delete_inputs_without_project)
    ]
