# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-26 12:53

from django.db import migrations


def find_marker_variants(apps, schema_editor):
    MarkerVariant = apps.get_model('projects', 'MarkerVariant')
    Label = apps.get_model('projects', 'Label')

    for l in Label.objects.all().iterator():
        try:
            l.marker_variant = MarkerVariant.objects.get(project=l.project, marker=l.marker)
            l.save()
        except MarkerVariant.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_auto_20210626_1216'),
    ]

    operations = [
        migrations.RunPython(find_marker_variants, migrations.RunPython.noop),
    ]
