# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-27 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fill_user_in_batches(apps, schema_editor):
    Batch = apps.get_model('projects', 'Batch')
    apps.get_model('projects', 'Input')
    apps.get_model('projects', 'Label')
    apps.get_model('projects', 'LabelRelation')

    for batch in Batch.objects.all().iterator():
        inp = batch.input_set.first()
        if inp:
            batch.user = inp.user
        else:
            lab = batch.label_set.first()
            if lab:
                batch.user = lab.user
            else:
                lab = batch.labelrelation_set.first()
                if lab:
                    batch.user = lab.user
        batch.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0106_auto_20210626_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(fill_user_in_batches, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='input',
            name='user',
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.RemoveField(
            model_name='labelrelation',
            name='user',
        ),
    ]
