# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_auto_20210627_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_intro_tour',
            field=models.BooleanField(default=False),
        ),
    ]
