# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-06-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_dataaccesslog_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='is_skipped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
