# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-12-01 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0110_dataaccesslog_is_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='context',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('PlainText', 'Plain text'), ('TextFile', 'Plain text file(s)'), ('Json', 'JSON file(s)'), ('TextsAPI', 'API')], max_length=10),
        ),
        migrations.AlterField(
            model_name='input',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='label',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='labelrelation',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='labelreview',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='level',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='actions',
            field=models.ManyToManyField(blank=True, help_text='Actions associated with each marker [EXPAND]', through='projects.MarkerContextMenuItem', to='projects.MarkerAction'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=models.CharField(choices=[('danger', 'Red'), ('success', 'Green'), ('warning', 'Yellow'), ('link', 'Dark Blue'), ('info', 'Light Blue'), ('primary', 'Teal'), ('black', 'Black'), ('grey', 'Grey'), ('warndark', 'Dark Yellow'), ('pink', 'Pink'), ('orange', 'Orange')], help_text="Marker's color used when annotating the text", max_length=10),
        ),
        migrations.AlterField(
            model_name='marker',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='for_task_type',
            field=models.CharField(blank=True, choices=[('qa', 'Question Answering'), ('ner', 'Named Entity Recognition'), ('corr', 'Coreference Resolution'), ('generic', 'Generic'), ('ranking', 'Ranking')], help_text='Specify task types (if any) for which this marker must be present (avaiable only to admins)', max_length=10),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(help_text='The display name of the marker (max 50 characters, must be unique)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='short',
            field=models.CharField(blank=True, help_text="Marker's nickname used internally (max 10 characters, must be unique,\n                     by default the capitalized first three character of the label)", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Keyboard shortcut for annotating a piece of text with this marker', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='markeraction',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='markercontextmenuitem',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='markerpair',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='markerrestriction',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='markerunit',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='markervariant',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='postprocessingmethod',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='premarker',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dt_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date, autofilled', null=True, verbose_name='creation date'),
        ),
    ]
