# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_copy_short_to_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='short',
        ),
        migrations.AlterField(
            model_name='marker',
            name='code',
            field=models.CharField(blank=True, help_text="Marker's nickname used internally", max_length=25, unique=True),
        ),
    ]
