# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2021-12-24 09:10

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0118_auto_20211223_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='suggestion_endpoint',
            field=models.URLField(blank=True, help_text='Endpoint for the Suggestions API', null=True),
        ),
        migrations.AddField(
            model_name='markervariant',
            name='are_suggestions_enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether Suggestions API should be enabled for this marker (if endpoint is specified)', verbose_name='enable suggestions?'),
        ),
        migrations.AddField(
            model_name='markervariant',
            name='custom_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Customized color for the annotated text span (color of the marker template by default)', max_length=18, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='markervariant',
            name='custom_shortcut',
            field=models.CharField(blank=True, help_text='Keyboard shortcut for annotating a piece of text with this marker (shortcut of the marker template by default', max_length=10, null=True, verbose_name='keyboard shortcut'),
        ),
        migrations.AddField(
            model_name='markervariant',
            name='custom_suggestion_endpoint',
            field=models.URLField(blank=True, help_text='\n            Custom endpoint for the Suggestions API (by default the one from the marker template is used).\n            Activates only if suggestions are enabled and the endpoint.\n            ', null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color for the annotated text span', max_length=18, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='markervariant',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.marker', verbose_name='marker template'),
        ),
    ]
