# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2021-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0121_auto_20211227_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], default='sv', help_text='Language of this data source', max_length=10, verbose_name='language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], default='sv', help_text='Language of this project', max_length=10, verbose_name='language'),
            preserve_default=False,
        ),
    ]
