# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-01-14 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0133_auto_20220113_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='range',
            options={'verbose_name': 'range', 'verbose_name_plural': 'ranges'},
        ),
        migrations.AddField(
            model_name='datasource',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('PlainText', 'Plain text'), ('TextFile', 'Plain text file(s)'), ('Json', 'JSON file(s)'), ('TextsAPI', 'Texts API')], max_length=10, verbose_name='dataset type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_finish',
            field=models.DateTimeField(verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dt_publish',
            field=models.DateTimeField(verbose_name='publishing date'),
        ),
    ]
