# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-01-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0134_auto_20220114_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='unit',
            new_name='group_order',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='unit',
            new_name='group_order',
        ),
        migrations.RenameField(
            model_name='labelrelation',
            old_name='unit',
            new_name='cluster'
        ),
        migrations.RemoveField(
            model_name='project',
            name='show_dataset_identifiers',
        ),
        migrations.AddField(
            model_name='project',
            name='show_datasource_identifiers',
            field=models.BooleanField(default=False, verbose_name='should data source identifiers be shown?'),
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='flags',
            field=models.TextField(default='', help_text='Additional information provided by the annotator', verbose_name='flags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disjoint_annotation',
            field=models.BooleanField(default=False, verbose_name='should each annotator work with their own part of data?'),
        ),
    ]
