# -*- coding: utf-8 -*-
# Generated by Django 3.2.10 on 2022-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0139_auto_20220218_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='markervariant',
            name='export_name',
            field=models.CharField(blank=True, help_text='The name of the field in the exported JSON file (English name by default)', max_length=50, null=True, verbose_name='export name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('PlainText', 'Plain text'), ('TextFile', 'Plain text file(s)'), ('Json', 'JSON file(s)'), ('DialJSL', 'Dialogue JSON lines'), ('TextsAPI', 'Texts API')], max_length=10, verbose_name='dataset type'),
        ),
    ]
