# -*- coding: utf-8 -*-
# Generated by Django 3.2.15 on 2022-08-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0142_auto_20220602_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_text_switch',
            field=models.BooleanField(default=True, help_text="Automatic mode involves showing a new text on page refresh if at least one annotation was made on it (default).\n                       If this setting is turned off, the annotator only gets a new text when they choose to click on the 'Get new text' button.", verbose_name='should annotation texts switch automatically?'),
        ),
    ]
