# -*- coding: utf-8 -*-
# Generated by Django 3.2.15 on 2022-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0143_project_auto_text_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccesslog',
            name='is_skipped',
            field=models.BooleanField(default=False, help_text='Indicates whether the datapoint was skipped by an annotator', verbose_name='is skipped?'),
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='Indicates whether the datapoint was successfully submitted by an annotator', verbose_name='is submitted?'),
        ),
    ]
