# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0156_auto_20221107_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.batch'),
        ),
    ]
