# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2022-11-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0157_batch_revision_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_editing',
            field=models.BooleanField(default=True, verbose_name='should editing of own annotations be allowed?'),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_reviewing',
            field=models.BooleanField(default=False, verbose_name='should peer reviewing be enabled?'),
        ),
    ]
