# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2023-01-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0161_celerytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='revision_changes',
            field=models.TextField(blank=True, help_text='The list of exact changes that were done to the object', null=True, verbose_name='revision changes'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('PlainText', 'Plain text'), ('TextFile', 'Plain text file(s)'), ('Json', 'JSON file(s)'), ('JsonLines', 'JSON lines'), ('TextsAPI', 'Texts API'), ('Interact', 'Interactive')], max_length=10, verbose_name='dataset type'),
        ),
        migrations.AlterField(
            model_name='input',
            name='revision_changes',
            field=models.TextField(blank=True, help_text='The list of exact changes that were done to the object', null=True, verbose_name='revision changes'),
        ),
        migrations.AlterField(
            model_name='label',
            name='revision_changes',
            field=models.TextField(blank=True, help_text='The list of exact changes that were done to the object', null=True, verbose_name='revision changes'),
        ),
    ]
