# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2023-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0162_auto_20230125_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_post_editing',
            field=models.BooleanField(default=False, verbose_name='should editing of own annotations AFTER finishing all of them be allowed?'),
        ),
    ]
