# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-20 11:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


# adapted from: https://stackoverflow.com/questions/43259865/adding-a-searchvectorfield-to-a-model-in-django
def index_context_content(apps, schema_editor):
    Context = apps.get_model("projects", "Context")
    Context.objects.update(
        content_vector=django.contrib.postgres.search.SearchVector('content', config='english_lite')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0163_project_allow_post_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='content_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.RunPython(index_context_content, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='context',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_vector'], name='projects_co_content_4f170f_gin'),
        ),
    ]
