# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0164_auto_20230220_1100'),
    ]

    # Adapted from https://pganalyze.com/blog/full-text-search-django-postgres
    operations = [
        migrations.RunSQL(
            sql='''
              CREATE TRIGGER projects_context_content_vector_trigger
              BEFORE INSERT OR UPDATE OF content, content_vector
              ON projects_context
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger(
                content_vector, 'public.english_lite', content
              );
            ''',

            reverse_sql = '''
              DROP TRIGGER IF EXISTS projects_context_content_vector_trigger
              ON projects_context;
            '''
        ),
    ]
