# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-21 15:57

import Textinator.ext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0165_create_context_content_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='search_config',
            field=Textinator.ext.RegConfigField(blank=True, null=True, verbose_name='PostgreSQL search config'),
        ),
    ]
