# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0165_create_context_content_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='search_config',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PostgreSQL search config'),
        ),
    ]
