# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-21 16:09

import Textinator.ext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0166_datasource_search_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='search_config',
            field=Textinator.ext.RegConfigField(blank=True, null=True, verbose_name='PostgreSQL search config'),
        ),
    ]
