# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-21 14:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.conf import settings


# adapted from: https://stackoverflow.com/questions/43259865/adding-a-searchvectorfield-to-a-model-in-django
def index_langdep_context_content(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Context = apps.get_model("projects", "Context")
    DataSource = apps.get_model("projects", "DataSource")

    lang_dict = dict(settings.LANGUAGES)
    sconf_dict = settings.LANG_SEARCH_CONFIG

    for ds in DataSource.objects.all():
        search_config = sconf_dict.get(
            ds.language,
            lang_dict.get(ds.language, 'english')
        ).lower()
        ds.search_config = search_config
        ds.save()
        Context.objects.filter(datasource=ds).update(
            search_config=search_config
        )

    for p in Project.objects.all():
        if p.language != 'en':
            search_config = sconf_dict.get(
                p.language,
                lang_dict.get(p.language, 'english')
            ).lower()

            Context.objects.filter(datasource__in=p.datasources.all()).update(
                content_vector=django.contrib.postgres.search.SearchVector(
                    'content', config=search_config)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0167_context_search_config'),
    ]

    operations = [
        migrations.RunPython(index_langdep_context_content, migrations.RunPython.noop),
        migrations.RunSQL(
            sql='''
              DROP TRIGGER IF EXISTS projects_context_content_vector_trigger
              ON projects_context;

              CREATE TRIGGER projects_context_content_vector_trigger
              BEFORE INSERT OR UPDATE OF content, content_vector
              ON projects_context
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger_column(
                content_vector, search_config, content
              );
            ''',

            reverse_sql = '''
              DROP TRIGGER IF EXISTS projects_context_content_vector_trigger
              ON projects_context;
            '''
        ),
    ]
