# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-02-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0168_update_context_content_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='extra',
            field=models.JSONField(blank=True, help_text='in a JSON format', null=True, verbose_name='extra information'),
        ),
        migrations.AddField(
            model_name='input',
            name='extra',
            field=models.JSONField(blank=True, help_text='in a JSON format', null=True, verbose_name='extra information'),
        ),
    ]
