# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0169_auto_20230224_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccesslog',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Indicates whether the log was programmatically marked as deleted (can't be set manually)", verbose_name='is marked as deleted?'),
        ),
    ]
