# -*- coding: utf-8 -*-
# Generated by Django 3.2.18 on 2023-03-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0170_dataaccesslog_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='datapoint',
            field=models.IntegerField(blank=True, help_text='As stored in the original dataset', null=True, verbose_name='datapoint ID'),
        ),
    ]
