# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2023-01-14 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StringTransformationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('batch', models.UUIDField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'string transformation',
                'verbose_name_plural': 'string transformations',
            },
        ),
        migrations.CreateModel(
            name='StringTransformationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(help_text='Action', verbose_name='action')),
                ('s_from', models.TextField(help_text='String to be transformed from', verbose_name='from')),
                ('s_to', models.TextField(help_text='String(s) to be transformed into, separated by |', verbose_name='to')),
                ('uuid', models.UUIDField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'string transformation rule',
                'verbose_name_plural': 'string transformation rules',
            },
        ),
        migrations.CreateModel(
            name='FailedTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='String to be filtered out', verbose_name='value')),
                ('transformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolbox_string_combinator.stringtransformationset', verbose_name='transformation')),
            ],
        ),
    ]
