# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2023-01-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_string_combinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringtransformationset',
            name='disabled',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stringtransformationset',
            name='rules',
            field=models.ManyToManyField(to='toolbox_string_combinator.StringTransformationRule'),
        ),
    ]
