# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2023-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox_string_combinator', '0003_stringtransformationrule_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringtransformationrule',
            name='s_to',
            field=models.TextField(blank=True, help_text='String(s) to be transformed into, separated by |', null=True, verbose_name='to'),
        ),
    ]
