# -*- coding: utf-8 -*-
# Generated by Django 3.2.16 on 2023-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211227_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_toolbox',
            field=models.BooleanField(default=False, verbose_name='enable toolbox?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('uk', 'Ukrainian')], default='en', max_length=10, verbose_name='preferred language'),
        ),
    ]
